// packages/markstream-angular/src/components/InlineCodeNode/InlineCodeNode.component.ts
import type { AngularRenderableNode } from '../shared/node-helpers'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-inline-code-node',
  standalone: true,
  template: '<code>{{ code }}</code>',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InlineCodeNodeComponent {
  @Input({ required: true }) node!: AngularRenderableNode

  get code() {
    return getString((this.node as any)?.code)
  }
}

// packages/markstream-svelte/src/components/InlineCodeNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { getString } from './shared/node-helpers'
  export let node: SvelteRenderableNode
  $: code = getString((node as any)?.code ?? (node as any)?.content ?? (node as any)?.raw)
</script>
<code class="inline-code-node">{code}</code>
