// packages/markstream-angular/src/components/MathBlockNode/MathBlockNode.component.ts
import { CommonModule } from '@angular/common'
import type { AfterViewInit, OnChanges, OnDestroy } from '@angular/core'
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  ViewChild,
  inject,
} from '@angular/core'
import { getKatex } from '../../optional/katex'
import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../../workers/katexWorkerClient'
import type { AngularRenderableNode } from '../shared/node-helpers'
import { getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-math-block-node',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="math-block markstream-nested-math-block" data-markstream-katex-managed="1">
      <div #mathRef class="markstream-nested-math-block__render" [class.math-rendering]="rendering"></div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MathBlockNodeComponent implements AfterViewInit, OnChanges, OnDestroy {
  private readonly cdr = inject(ChangeDetectorRef)

  @ViewChild('mathRef') private mathRef?: ElementRef<HTMLDivElement>

  @Input({ required: true }) node!: AngularRenderableNode

  rendering = true

  private destroyed = false
  private renderVersion = 0
  private hasRenderedOnce = false

  get content() {
    return getString((this.node as any)?.content || (this.node as any)?.markup || (this.node as any)?.raw)
  }

  ngAfterViewInit() {
    void this.renderMath()
  }

  ngOnChanges() {
    if (!this.mathRef)
      return
    void this.renderMath()
  }

  ngOnDestroy() {
    this.destroyed = true
    this.renderVersion += 1
  }

  private async renderMath() {
    const target = this.mathRef?.nativeElement
    if (!target)
      return

    const content = this.content
    const version = ++this.renderVersion
    if (!content) {
      target.textContent = ''
      this.rendering = false
      this.cdr.markForCheck()
      return
    }

    if (!this.hasRenderedOnce)
      this.rendering = true

    const html = await this.resolveKatexMarkup(content)
    if (this.destroyed || version !== this.renderVersion)
      return

    if (html) {
      target.innerHTML = html
      this.hasRenderedOnce = true
      this.rendering = false
    }
    else if (!(this.node as any)?.loading) {
      target.textContent = getString((this.node as any)?.raw || content)
      this.rendering = false
    }

    this.cdr.markForCheck()
  }

  private async resolveKatexMarkup(content: string) {
    try {
      return await renderKaTeXWithBackpressure(content, true, {
        timeout: 3000,
        waitTimeout: 2000,
        maxRetries: 1,
      })
    }
    catch (error: any) {
      const code = error?.code || error?.name
      const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || error?.fallbackToRenderer
      const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
      if (!isWorkerInitFailure && !isBusyOrTimeout)
        return null
    }

    const katex = await getKatex()
    if (!katex)
      return null

    try {
      const html = katex.renderToString(content, {
        throwOnError: (this.node as any)?.loading === true,
        displayMode: true,
      })
      setKaTeXCache(content, true, html)
      return html
    }
    catch {
      return null
    }
  }
}

// packages/markstream-svelte/src/components/MathBlockNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { onDestroy } from 'svelte'
  import { getKatex } from '../optional/katex'
  import { normalizeKaTeXRenderInput } from '../utils/normalizeKaTeXRenderInput'
  import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../workers/katexWorkerClient'
  import { getString } from './shared/node-helpers'

  export let node: SvelteRenderableNode

  let mathEl: HTMLDivElement | null = null
  let rendering = true
  let destroyed = false
  let renderVersion = 0
  let hasRenderedOnce = false

  $: source = getString((node as any)?.content || (node as any)?.markup || (node as any)?.raw)
  $: raw = getString((node as any)?.raw || source)
  $: nodeLoading = (node as any)?.loading === true
  $: renderKey = `${source}\n${raw}\n${nodeLoading ? '1' : '0'}`
  $: if (mathEl)
    void renderMath(renderKey, source, raw, nodeLoading)

  onDestroy(() => {
    destroyed = true
    renderVersion += 1
  })

  async function renderMath(_renderKey: string, currentSource: string, currentRaw: string, currentLoading: boolean) {
    const target = mathEl
    if (!target)
      return

    const content = normalizeKaTeXRenderInput(currentSource)
    const version = ++renderVersion
    if (!content) {
      target.textContent = ''
      rendering = false
      return
    }

    if (!hasRenderedOnce)
      rendering = true

    const html = await resolveKatexMarkup(content, currentLoading)
    if (destroyed || version !== renderVersion)
      return

    if (html) {
      target.innerHTML = html
      hasRenderedOnce = true
      rendering = false
    }
    else if (!currentLoading) {
      target.textContent = currentRaw || content
      rendering = false
    }
  }

  async function resolveKatexMarkup(content: string, currentLoading: boolean) {
    try {
      return await renderKaTeXWithBackpressure(content, true, {
        timeout: 3000,
        waitTimeout: 2000,
        maxRetries: 1,
      })
    }
    catch (error: any) {
      const code = error?.code || error?.name
      const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || error?.fallbackToRenderer
      const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
      if (!isWorkerInitFailure && !isBusyOrTimeout)
        return null
    }

    const katex = await getKatex()
    if (!katex)
      return null

    try {
      const html = katex.renderToString(content, {
        throwOnError: currentLoading,
        displayMode: true,
      })
      setKaTeXCache(content, true, html)
      return html
    }
    catch {
      return null
    }
  }
</script>

<div class="math-block markstream-nested-math-block" data-markstream-katex-managed="1">
  <div bind:this={mathEl} class:math-rendering={rendering} class="markstream-nested-math-block__render"></div>
</div>
