// packages/markstream-angular/src/components/TextNode/TextNode.component.ts
import type { OnChanges } from '@angular/core'
import type { AngularRenderableNode, AngularRenderContext } from '../shared/node-helpers'
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { getString } from '../shared/node-helpers'
import { resolveStreamingTextState } from 'markstream-core'

@Component({
  selector: 'markstream-angular-text-node',
  standalone: true,
  imports: [CommonModule],
  template: `
    <ng-container *ngIf="!centered; else centeredText">
      <span class="markstream-angular-text-node">
        <span *ngIf="settledText">{{ settledText }}</span>
        <span
          *ngIf="streamedDelta"
          [class]="'markstream-angular-text__stream-delta ' + streamedDeltaClass"
          (animationend)="settleStreamedDelta()"
        >{{ streamedDelta }}</span>
      </span>
    </ng-container>
    <ng-template #centeredText>
      <span class="markstream-angular-text-node markstream-angular-text--centered">
        <span *ngIf="settledText">{{ settledText }}</span>
        <span
          *ngIf="streamedDelta"
          [class]="'markstream-angular-text__stream-delta ' + streamedDeltaClass"
          (animationend)="settleStreamedDelta()"
        >{{ streamedDelta }}</span>
      </span>
    </ng-template>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TextNodeComponent implements OnChanges {
  @Input({ required: true }) node!: AngularRenderableNode
  @Input() context?: AngularRenderContext
  @Input() indexKey?: string
  @Input() typewriter?: boolean

  settledText = ''
  streamedDelta = ''
  private streamFadeVersion = 0
  private lastStreamRenderVersion?: number

  ngOnChanges() {
    const nextText = getString((this.node as any)?.content)
    const streamStateKey = getString(this.indexKey).trim()
    const textStreamState = this.context?.textStreamState
    const streamRenderVersion = this.context?.streamRenderVersion
    const streamRenderVersionChanged = streamRenderVersion !== this.lastStreamRenderVersion
    const rendered = `${this.settledText}${this.streamedDelta}`
    const previousPersisted = streamStateKey
      ? textStreamState?.get(streamStateKey)
      : undefined
    const previousText = previousPersisted ?? rendered

    if (!this.typewriterEnabled) {
      this.settledText = nextText
      this.streamedDelta = ''
      if (streamStateKey)
        textStreamState?.set(streamStateKey, nextText)
      this.lastStreamRenderVersion = streamRenderVersion
      return
    }

    if (nextText === previousText) {
      if (this.streamedDelta && streamRenderVersionChanged) {
        this.settleStreamedDelta()
      }
      else if (rendered !== nextText) {
        this.settledText = nextText
        this.streamedDelta = ''
      }
      if (streamStateKey)
        textStreamState?.set(streamStateKey, nextText)
      this.lastStreamRenderVersion = streamRenderVersion
      return
    }

    const nextState = resolveStreamingTextState({
      nextContent: nextText,
      previousContent: previousText,
      typewriterEnabled: this.typewriterEnabled,
    })

    this.settledText = nextState.settledContent
    this.streamedDelta = nextState.streamedDelta
    if (nextState.appended)
      this.streamFadeVersion += 1
    if (streamStateKey)
      textStreamState?.set(streamStateKey, nextText)
    this.lastStreamRenderVersion = streamRenderVersion
  }

  get centered() {
    return !!(this.node as any)?.center
  }

  get streamedDeltaClass() {
    return this.streamFadeVersion % 2 === 0
      ? 'markstream-angular-text__stream-delta--a'
      : 'markstream-angular-text__stream-delta--b'
  }

  get typewriterEnabled() {
    if (typeof this.typewriter === 'boolean')
      return this.typewriter
    if (typeof this.context?.typewriter === 'boolean')
      return this.context.typewriter
    return true
  }

  settleStreamedDelta() {
    if (!this.streamedDelta)
      return
    this.settledText = `${this.settledText}${this.streamedDelta}`
    this.streamedDelta = ''
  }
}

// packages/markstream-svelte/src/components/TextNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode, SvelteRenderContext } from './shared/node-helpers'
  import { resolveStreamingTextState } from 'markstream-core'
  import { getString } from './shared/node-helpers'

  interface Props {
    node: SvelteRenderableNode
    context?: SvelteRenderContext
    indexKey?: string | number
    typewriter?: boolean
  }

  let {
    node,
    context = undefined,
    indexKey = undefined,
    typewriter = undefined
  }: Props = $props()

  let previousKey = ''
  let previousContent = ''
  let deltaClass = 'markstream-svelte-text__stream-delta--a'

  const content = $derived(getString((node as any)?.content ?? (node as any)?.raw))
  const centered = $derived(Boolean((node as any)?.center))
  const streamKey = $derived(String(context?.customId ?? 'global') + ':' + String(context?.streamRenderVersion ?? 0) + ':' + String(indexKey ?? 'node'))

  const streamInfo = $derived.by(() => {
    const state = context?.textStreamState
    const previous = streamKey === previousKey ? previousContent : (state?.get(streamKey) ?? '')

    const result = resolveStreamingTextState({
      nextContent: content,
      previousContent: previous,
      typewriterEnabled: typewriter !== false,
    })

    if (result.appended)
      deltaClass = deltaClass.endsWith('--a') ? 'markstream-svelte-text__stream-delta--b' : 'markstream-svelte-text__stream-delta--a'

    previousKey = streamKey
    previousContent = content
    state?.set(streamKey, content)

    return { stableContent: result.settledContent, deltaContent: result.streamedDelta, deltaClass }
  })
</script>

<span data-typewriter={typewriter !== false ? '1' : undefined} class:markstream-svelte-text--centered={centered} class="markstream-svelte-text-node text-node">{streamInfo.stableContent}{#if streamInfo.deltaContent}<span class="markstream-svelte-text__stream-delta text-node-stream-delta {streamInfo.deltaClass}">{streamInfo.deltaContent}</span>{/if}</span>
