// packages/markstream-react/src/components/CodeBlockNode/HtmlPreviewFrame.tsx
import React, { useEffect, useMemo } from 'react'
import { createPortal } from 'react-dom'
import { useSafeI18n } from '../../i18n/useSafeI18n'

const isDevEnv = typeof import.meta !== 'undefined' && Boolean(import.meta.env?.DEV)
let lastWarnedDangerousSandbox: string | null = null

function normalizeSandboxTokens(value: string) {
  return new Set(
    value
      .trim()
      .toLowerCase()
      .split(/\s+/)
      .filter(Boolean),
  )
}

function warnDangerousHtmlPreviewSandbox(value: string) {
  if (!isDevEnv || typeof console === 'undefined' || lastWarnedDangerousSandbox === value)
    return
  const tokens = normalizeSandboxTokens(value)
  if (tokens.has('allow-scripts') && tokens.has('allow-same-origin')) {
    lastWarnedDangerousSandbox = value
    console.warn('[markstream-react] htmlPreviewSandbox contains both allow-scripts and allow-same-origin. Use this only for fully trusted content served from an isolated origin.')
  }
}

function resolveHtmlPreviewSandboxValue(htmlPreviewSandbox: unknown, htmlPreviewAllowScripts?: boolean) {
  if (typeof htmlPreviewSandbox === 'string') {
    warnDangerousHtmlPreviewSandbox(htmlPreviewSandbox)
    return htmlPreviewSandbox
  }
  if (htmlPreviewSandbox !== undefined)
    return ''
  return htmlPreviewAllowScripts === true ? 'allow-scripts' : ''
}

export interface HtmlPreviewFrameProps {
  code: string
  isDark?: boolean
  htmlPreviewAllowScripts?: boolean
  htmlPreviewSandbox?: string
  onClose?: () => void
  title?: string
}

export function HtmlPreviewFrame(props: HtmlPreviewFrameProps) {
  const { t } = useSafeI18n()
  const srcdoc = useMemo(() => {
    const base = props.code || ''
    const lowered = base.trim().toLowerCase()
    if (lowered.startsWith('<!doctype') || lowered.startsWith('<html') || lowered.startsWith('<body'))
      return base
    const bg = props.isDark ? '#020617' : '#ffffff'
    const fg = props.isDark ? '#e5e7eb' : '#020617'
    return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        background-color: ${bg};
        color: ${fg};
      }
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'SF Pro Text', ui-sans-serif, sans-serif;
      }
    </style>
  </head>
  <body>
    ${base}
  </body>
</html>`
  }, [props.code, props.isDark])

  const sandboxValue = useMemo(() => {
    return resolveHtmlPreviewSandboxValue(props.htmlPreviewSandbox, props.htmlPreviewAllowScripts)
  }, [props.htmlPreviewAllowScripts, props.htmlPreviewSandbox])

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape' || event.key === 'Esc')
        props.onClose?.()
    }
    if (typeof window !== 'undefined')
      window.addEventListener('keydown', handleKeydown)
    return () => {
      if (typeof window !== 'undefined')
        window.removeEventListener('keydown', handleKeydown)
    }
  }, [props])

  if (typeof document === 'undefined')
    return null

  return createPortal(
    <div className={`html-preview-frame__backdrop${props.isDark ? ' html-preview-frame__backdrop--dark' : ''}`} onClick={() => props.onClose?.()}>
      <div className={`html-preview-frame${props.isDark ? ' html-preview-frame--dark' : ''}`} onClick={e => e.stopPropagation()}>
        <div className="html-preview-frame__header">
          <div className="html-preview-frame__title">
            <span className="html-preview-frame__dot" />
            <span className="html-preview-frame__label">{props.title || `HTML ${t('common.preview')}`}</span>
          </div>
          <button
            type="button"
            className={`html-preview-frame__close${props.isDark ? ' html-preview-frame__close--dark' : ''}`}
            onClick={() => props.onClose?.()}
          >
            ×
          </button>
        </div>
        <iframe
          className="html-preview-frame__iframe"
          sandbox={sandboxValue}
          src="about:blank"
          srcDoc={srcdoc}
          title={props.title || 'Preview'}
        />
      </div>
    </div>,
    document.body,
  )
}

export default HtmlPreviewFrame

// packages/markstream-vue2/src/components/CodeBlockNode/HtmlPreviewFrame.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue-demi'
import { useSafeI18n } from '../../composables/useSafeI18n'
import Portal from '../Portal'

const props = defineProps<{
  code: string
  isDark?: boolean
  htmlPreviewAllowScripts?: boolean
  htmlPreviewSandbox?: string
  onClose?: () => void
  title?: string
}>()

const isDevEnv = typeof import.meta !== 'undefined' && Boolean(import.meta.env?.DEV)
let lastWarnedDangerousSandbox: string | null = null

function normalizeSandboxTokens(value: string) {
  return new Set(
    value
      .trim()
      .toLowerCase()
      .split(/\s+/)
      .filter(Boolean),
  )
}

function warnDangerousHtmlPreviewSandbox(value: string) {
  if (!isDevEnv || typeof console === 'undefined' || lastWarnedDangerousSandbox === value)
    return
  const tokens = normalizeSandboxTokens(value)
  if (tokens.has('allow-scripts') && tokens.has('allow-same-origin')) {
    lastWarnedDangerousSandbox = value
    console.warn('[markstream-vue2] htmlPreviewSandbox contains both allow-scripts and allow-same-origin. Use this only for fully trusted content served from an isolated origin.')
  }
}

function resolveHtmlPreviewSandboxValue(htmlPreviewSandbox: unknown, htmlPreviewAllowScripts?: boolean) {
  if (typeof htmlPreviewSandbox === 'string') {
    warnDangerousHtmlPreviewSandbox(htmlPreviewSandbox)
    return htmlPreviewSandbox
  }
  if (htmlPreviewSandbox !== undefined)
    return ''
  return htmlPreviewAllowScripts === true ? 'allow-scripts' : ''
}

const { t } = useSafeI18n()

const srcdoc = computed(() => {
  const base = props.code || ''
  // 如果用户已经自己写了 <html>/<body>，直接原样输出，避免重复包裹
  const lowered = base.trim().toLowerCase()
  if (lowered.startsWith('<!doctype') || lowered.startsWith('<html') || lowered.startsWith('<body'))
    return base

  const bg = props.isDark ? '#020617' : '#ffffff'
  const fg = props.isDark ? '#e5e7eb' : '#020617'

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      html, body {
        margin: 0;
        padding: 0;
        height: 100%;
        background-color: ${bg};
        color: ${fg};
      }
      body {
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'SF Pro Text', ui-sans-serif, sans-serif;
      }
    </style>
  </head>
  <body>
    ${base}
  </body>
</html>`
})

const sandboxValue = computed(() => {
  return resolveHtmlPreviewSandboxValue(props.htmlPreviewSandbox, props.htmlPreviewAllowScripts)
})

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Escape' || e.key === 'Esc')
    props.onClose?.()
}

onMounted(() => {
  if (typeof window !== 'undefined')
    window.addEventListener('keydown', handleKeydown)
})

onUnmounted(() => {
  if (typeof window !== 'undefined')
    window.removeEventListener('keydown', handleKeydown)
})
</script>

<template>
  <Portal to="body">
    <div class="markstream-vue2">
      <div class="html-preview-frame__backdrop" :class="{ 'html-preview-frame__backdrop--dark': props.isDark }" @click="props.onClose?.()">
        <div class="html-preview-frame" :class="{ 'html-preview-frame--dark': props.isDark }" @click.stop>
          <div class="html-preview-frame__header">
            <div class="html-preview-frame__title">
              <span class="html-preview-frame__dot" />
              <span class="html-preview-frame__label">{{ props.title || t('common.preview') || 'Preview' }}</span>
            </div>
            <button
              type="button"
              class="html-preview-frame__close"
              :class="{ 'html-preview-frame__close--dark': props.isDark }"
              @click="props.onClose?.()"
            >
              ×
            </button>
          </div>
          <iframe
            class="html-preview-frame__iframe"
            :sandbox="sandboxValue"
            :srcdoc="srcdoc"
          />
        </div>
      </div>
    </div>
  </Portal>
</template>

<style scoped>
.html-preview-frame__backdrop {
  position: fixed;
  inset: 0;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 50;
}

.html-preview-frame__backdrop--dark {
  background-color: rgba(15, 23, 42, 0.8);
}

.html-preview-frame {
  width: 80vw;
  max-width: 960px;
  height: 70vh;
  background-color: #fff;
  border-radius: 0.5rem;
  overflow: hidden;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.25);
  display: flex;
  flex-direction: column;
}

.html-preview-frame--dark {
  background-color: #020617;
  color: #e5e7eb;
  box-shadow: 0 10px 40px rgba(0, 0, 0, 0.6);
}

.html-preview-frame__header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0.4rem 0.75rem;
  border-bottom: 1px solid rgba(0, 0, 0, 0.06);
}

.html-preview-frame--dark .html-preview-frame__header {
  border-bottom-color: rgba(148, 163, 184, 0.35);
}

.html-preview-frame__title {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.75rem;
  font-weight: 500;
  letter-spacing: 0.02em;
  text-transform: uppercase;
  opacity: 0.85;
}

.html-preview-frame__dot {
  width: 0.5rem;
  height: 0.5rem;
  border-radius: 999px;
  background-color: #22c55e;
}

.html-preview-frame--dark .html-preview-frame__dot {
  background-color: #4ade80;
}

.html-preview-frame__label {
  white-space: nowrap;
}

.html-preview-frame__close {
  border: none;
  background: transparent;
  font-size: 1.25rem;
  line-height: 1;
  cursor: pointer;
}

.html-preview-frame__close--dark {
  color: #e5e7eb;
}

.html-preview-frame__iframe {
  width: 100%;
  height: 100%;
  border: none;
  display: block;
}

@media (max-width: 640px) {
  .html-preview-frame {
    width: 100vw;
    height: 80vh;
    border-radius: 0;
  }
}
</style>
