// packages/markstream-svelte/src/components/PreCodeNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { encodeDataPayload, getString, sanitizeClassToken } from './shared/node-helpers'
  export let node: SvelteRenderableNode
  $: languageRaw = getString((node as any)?.language).trim()
  $: language = sanitizeClassToken(languageRaw)
  $: code = getString((node as any)?.code)
  $: diff = Boolean((node as any)?.diff)
  $: loading = (node as any)?.loading === true
</script>
{#if !(loading && !code.trim())}
  <pre data-markstream-code-block="1" data-markstream-language={languageRaw || undefined} data-markstream-loading={loading ? '1' : undefined} data-markstream-diff={diff ? '1' : undefined} data-markstream-original={diff ? encodeDataPayload(getString((node as any)?.originalCode)) : undefined} data-markstream-updated={diff ? encodeDataPayload(getString((node as any)?.updatedCode)) : undefined} aria-busy={loading ? 'true' : undefined}><code class={language ? 'language-' + language : undefined}>{code}</code></pre>
{/if}

// packages/markstream-angular/src/components/PreCodeNode/PreCodeNode.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import type { AngularRenderableNode } from '../shared/node-helpers'
import { getString, normalizeCodeLanguage } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-pre-code-node',
  standalone: true,
  template: `
    <pre
      [class]="languageClass"
      [attr.aria-busy]="loading"
      [attr.aria-label]="ariaLabel"
      [attr.data-language]="language"
      tabindex="0"
    >
      <code translate="no">{{ code }}</code>
    </pre>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PreCodeNodeComponent {
  @Input({ required: true }) node!: AngularRenderableNode

  get language() {
    return normalizeCodeLanguage((this.node as any)?.language)
  }

  get languageClass() {
    return `language-${this.language}`
  }

  get ariaLabel() {
    return this.language ? `Code block: ${this.language}` : 'Code block'
  }

  get code() {
    return getString((this.node as any)?.code)
  }

  get loading() {
    return (this.node as any)?.loading === true
  }
}
