// packages/markstream-svelte/src/components/FootnoteAnchorNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { getString } from './shared/node-helpers'

  export let node: SvelteRenderableNode

  $: id = getString((node as any)?.id)
  $: href = id ? `#fnref-${id}` : undefined

  function scrollToReference(event: MouseEvent) {
    event.preventDefault()
    if (typeof document === 'undefined' || !id)
      return
    const target = document.getElementById(`fnref-${id}`)
    target?.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }
</script>

<a class="footnote-anchor" href={href} title={id ? `返回引用 ${id}` : undefined} onclick={scrollToReference}>
  ↩︎
</a>

// src/components/FootnoteAnchorNode/FootnoteAnchorNode.vue
<script setup lang="ts">
const props = defineProps<{ node: { type: 'footnote_anchor', id: string, raw?: string } }>()

function scrollToReference(e: MouseEvent) {
  e.preventDefault()
  if (typeof document === 'undefined')
    return
  const id = `fnref-${String(props.node.id ?? '')}`
  const anchors = document.getElementById(id)
  if (anchors) {
    anchors.scrollIntoView({ behavior: 'smooth', block: 'center' })
  }
}
</script>

<template>
  <a
    class="footnote-anchor text-sm hover:underline cursor-pointer"
    :href="`#fnref-${node.id}`"
    :title="`返回引用 ${node.id}`"
    @click="scrollToReference"
  >
    ↩︎
  </a>
</template>

<style scoped>
.footnote-anchor {
  margin-left: 0.5rem;
  color: var(--link-color);
}
</style>
