// playground-react19/src/App.tsx
import { Icon } from '@iconify/react'
import { NodeRenderer, setCustomComponents, setKaTeXWorker, setMermaidWorker } from 'markstream-react'
import KatexWorker from 'markstream-react/workers/katexRenderer.worker?worker&inline'
import MermaidWorker from 'markstream-react/workers/mermaidParser.worker?worker&inline'
import { memo, startTransition, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { TestLab } from '../../playground-react18/src/shared/TestLab'
import { ThinkingNode } from './components/ThinkingNode'
import { streamContent } from './markdown'

setKaTeXWorker(new KatexWorker())
setMermaidWorker(new MermaidWorker())
const PLAYGROUND_CUSTOM_ID = 'playground-demo'
setCustomComponents(PLAYGROUND_CUSTOM_ID, {
  thinking: ThinkingNode,
})

const MemoizedNodeRenderer = memo(NodeRenderer)

const THEMES = [
  'andromeeda',
  'aurora-x',
  'ayu-dark',
  'catppuccin-frappe',
  'catppuccin-latte',
  'catppuccin-macchiato',
  'catppuccin-mocha',
  'dark-plus',
  'dracula',
  'dracula-soft',
  'everforest-dark',
  'everforest-light',
  'github-dark',
  'github-dark-default',
  'github-dark-dimmed',
  'github-dark-high-contrast',
  'github-light',
  'github-light-default',
  'github-light-high-contrast',
  'gruvbox-dark-hard',
  'gruvbox-dark-medium',
  'gruvbox-dark-soft',
  'gruvbox-light-hard',
  'gruvbox-light-medium',
  'gruvbox-light-soft',
  'houston',
  'kanagawa-dragon',
  'kanagawa-lotus',
  'kanagawa-wave',
  'laserwave',
  'light-plus',
  'material-theme',
  'material-theme-darker',
  'material-theme-lighter',
  'material-theme-ocean',
  'material-theme-palenight',
  'min-dark',
  'min-light',
  'monokai',
  'night-owl',
  'nord',
  'one-dark-pro',
  'one-light',
  'plastic',
  'poimandres',
  'red',
  'rose-pine',
  'rose-pine-dawn',
  'rose-pine-moon',
  'slack-dark',
  'slack-ochin',
  'snazzy-light',
  'solarized-dark',
  'solarized-light',
  'synthwave-84',
  'tokyo-night',
  'vesper',
  'vitesse-black',
  'vitesse-dark',
  'vitesse-light',
] as const

const STREAM_DELAY_KEY = 'vmr-settings-stream-delay'
const STREAM_CHUNK_KEY = 'vmr-settings-stream-chunk-size'
const THEME_KEYS = ['vmr-settings-selected-theme', 'vmv-settings-selected-theme'] as const
const DARK_MODE_KEY = 'vueuse-color-scheme'

function clampDelay(value: number) {
  if (!Number.isFinite(value))
    return 16
  return Math.min(200, Math.max(4, Math.round(value)))
}

function clampChunk(value: number) {
  if (!Number.isFinite(value))
    return 1
  return Math.min(16, Math.max(1, Math.floor(value)))
}

function formatThemeName(theme: string) {
  return theme
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function readNumber(key: string, fallback: number) {
  if (typeof window === 'undefined')
    return fallback
  const raw = window.localStorage.getItem(key)
  if (!raw)
    return fallback
  const parsed = Number(raw)
  return Number.isFinite(parsed) ? parsed : fallback
}

function readThemeFromStorage(fallback: string) {
  if (typeof window === 'undefined')
    return fallback
  for (const key of THEME_KEYS) {
    const raw = window.localStorage.getItem(key)
    if (raw && raw.trim())
      return raw
  }
  return fallback
}

function normalizePath(pathname: string) {
  const normalized = pathname.replace(/\/+$/, '')
  return normalized || '/'
}

export default function App() {
  const [content, setContent] = useState('')
  const [currentPath, setCurrentPath] = useState(() => {
    if (typeof window === 'undefined')
      return '/'
    return normalizePath(window.location.pathname)
  })
  const [showSettings, setShowSettings] = useState(false)
  const [selectedTheme, setSelectedTheme] = useState(() => readThemeFromStorage('vitesse-dark'))
  const [streamDelay, setStreamDelay] = useState(() => clampDelay(readNumber(STREAM_DELAY_KEY, 16)))
  const [streamChunkSize, setStreamChunkSize] = useState(() => clampChunk(readNumber(STREAM_CHUNK_KEY, 1)))
  const [isDark, setIsDark] = useState(() => {
    if (typeof window === 'undefined')
      return false
    const stored = window.localStorage.getItem(DARK_MODE_KEY)
    if (stored)
      return stored === 'dark'
    return window.matchMedia?.('(prefers-color-scheme: dark)').matches ?? false
  })

  const normalizedChunkSize = useMemo(() => clampChunk(streamChunkSize), [streamChunkSize])
  const themeOptions = useMemo(() => Array.from(THEMES), [])
  const messagesRef = useRef<HTMLDivElement | null>(null)
  const frameRef = useRef<number | null>(null)
  const settingsRootRef = useRef<HTMLDivElement | null>(null)
  const isTestPage = currentPath === '/test'

  const navigate = useCallback((pathname: string) => {
    if (typeof window === 'undefined')
      return
    const nextPath = normalizePath(pathname)
    if (nextPath !== normalizePath(window.location.pathname))
      window.history.pushState({}, '', nextPath)
    startTransition(() => {
      setCurrentPath(nextPath)
    })
  }, [])

  useEffect(() => {
    if (typeof window === 'undefined')
      return
    const handlePopState = () => {
      startTransition(() => {
        setCurrentPath(normalizePath(window.location.pathname))
      })
    }
    window.addEventListener('popstate', handlePopState)
    return () => {
      window.removeEventListener('popstate', handlePopState)
    }
  }, [])

  useEffect(() => {
    if (typeof document === 'undefined')
      return
    document.documentElement.classList.toggle('dark', isDark)
    if (typeof window !== 'undefined')
      window.localStorage.setItem(DARK_MODE_KEY, isDark ? 'dark' : 'light')
  }, [isDark])

  useEffect(() => {
    const bounded = clampDelay(streamDelay)
    if (bounded !== streamDelay) {
      setStreamDelay(bounded)
      return
    }
    if (typeof window !== 'undefined')
      window.localStorage.setItem(STREAM_DELAY_KEY, String(bounded))
  }, [streamDelay])

  useEffect(() => {
    const bounded = clampChunk(streamChunkSize)
    if (bounded !== streamChunkSize) {
      setStreamChunkSize(bounded)
      return
    }
    if (typeof window !== 'undefined')
      window.localStorage.setItem(STREAM_CHUNK_KEY, String(bounded))
  }, [streamChunkSize])

  useEffect(() => {
    if (typeof window === 'undefined')
      return
    for (const key of THEME_KEYS)
      window.localStorage.setItem(key, selectedTheme)
  }, [selectedTheme])

  const scheduleCheckMinHeight = useCallback(() => {
    if (typeof window === 'undefined')
      return
    if (frameRef.current != null)
      return
    frameRef.current = window.requestAnimationFrame(() => {
      frameRef.current = null
      const container = messagesRef.current
      if (!container)
        return
      const renderer = container.querySelector('.markdown-renderer') as HTMLElement | null
      if (!renderer)
        return
      const shouldDisable = renderer.scrollHeight > container.clientHeight
      if (shouldDisable) {
        renderer.classList.add('disable-min-height')
      }
      else {
        renderer.classList.remove('disable-min-height')
      }
    })
  }, [])

  useEffect(() => {
    const container = messagesRef.current
    if (!container)
      return
    scheduleCheckMinHeight()

    const roContainer = new ResizeObserver(scheduleCheckMinHeight)
    roContainer.observe(container)

    let roContent: ResizeObserver | null = null
    let lastRenderer: Element | null = null
    const observeContent = () => {
      const renderer = container.querySelector('.markdown-renderer')
      if (!renderer)
        return
      if (renderer === lastRenderer && roContent)
        return
      lastRenderer = renderer
      if (roContent)
        roContent.disconnect()
      roContent = new ResizeObserver(scheduleCheckMinHeight)
      roContent.observe(renderer)
    }
    observeContent()

    let mutationFrame: number | null = null
    const mo = new MutationObserver(() => {
      if (mutationFrame != null)
        return
      mutationFrame = window.requestAnimationFrame(() => {
        mutationFrame = null
        observeContent()
        scheduleCheckMinHeight()
      })
    })
    mo.observe(container, { childList: true, subtree: true })

    return () => {
      roContainer.disconnect()
      roContent?.disconnect()
      mo.disconnect()
      if (mutationFrame != null)
        window.cancelAnimationFrame(mutationFrame)
    }
  }, [scheduleCheckMinHeight])

  useEffect(() => {
    scheduleCheckMinHeight()
  }, [content, scheduleCheckMinHeight])

  useEffect(() => {
    return () => {
      if (frameRef.current != null)
        window.cancelAnimationFrame(frameRef.current)
    }
  }, [])

  useEffect(() => {
    if (!showSettings)
      return
    const handlePointerDown = (event: MouseEvent | TouchEvent) => {
      const root = settingsRootRef.current
      if (!root)
        return
      if (root.contains(event.target as Node))
        return
      setShowSettings(false)
    }
    document.addEventListener('mousedown', handlePointerDown)
    document.addEventListener('touchstart', handlePointerDown)
    return () => {
      document.removeEventListener('mousedown', handlePointerDown)
      document.removeEventListener('touchstart', handlePointerDown)
    }
  }, [showSettings])

  useEffect(() => {
    if (isTestPage || typeof window === 'undefined')
      return
    let timer: number | null = null
    const startStreaming = () => {
      timer = window.setInterval(() => {
        setContent((current) => {
          if (current.length >= streamContent.length) {
            if (timer != null) {
              window.clearInterval(timer)
              timer = null
            }
            return current
          }
          const nextChunk = streamContent.slice(current.length, current.length + normalizedChunkSize)
          return current + nextChunk
        })
      }, streamDelay)
    }
    startStreaming()
    return () => {
      if (timer != null)
        window.clearInterval(timer)
    }
  }, [isTestPage, streamDelay, normalizedChunkSize])

  const goToTest = () => {
    navigate('/test')
  }

  if (isTestPage)
    return <TestLab frameworkLabel="React 19" onGoHome={() => navigate('/')} />

  return (
    <div className="markstream-vue h-full">
      <div className="flex items-center justify-center p-4 app-container h-full bg-gray-50 dark:bg-gray-900">
        <div ref={settingsRootRef} className="fixed top-4 right-4 z-10 pointer-events-none flex flex-col items-end gap-2">
          <button
            type="button"
            className={`pointer-events-auto settings-toggle w-10 h-10 rounded-full bg-white/95 dark:bg-gray-800/95 backdrop-blur-md border border-gray-200/50 dark:border-gray-700/50 hover:bg-gray-50 dark:hover:bg-gray-700/50 shadow-lg dark:shadow-gray-900/20 transition-all duration-200 flex items-center justify-center focus:outline-none focus:ring-2 focus:ring-blue-500/50 ${showSettings ? 'ring-2 ring-blue-500/50' : ''}`}
            onClick={() => setShowSettings(value => !value)}
          >
            <Icon
              icon="carbon:settings"
              className={`w-5 h-5 text-gray-600 dark:text-gray-400 transition-transform duration-200 ${showSettings ? 'rotate-90' : ''}`}
            />
          </button>

          {showSettings && (
            <div
              className="pointer-events-auto settings-panel absolute top-12 right-0 mt-2 bg-white/95 dark:bg-gray-800/95 backdrop-blur-md border border-gray-200/50 dark:border-gray-700/50 rounded-xl shadow-xl dark:shadow-gray-900/30 p-4 space-y-4 min-w-[220px] origin-top-right transition-all duration-200 ease-out"
            >
              <div className="space-y-2">
                <label className="block text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase tracking-wide">
                  Code Theme
                </label>
                <div className="relative theme-selector">
                  <select
                    value={selectedTheme}
                    onChange={event => setSelectedTheme(event.target.value)}
                    className="w-full appearance-none px-3 py-2 pr-8 bg-gray-50 dark:bg-gray-700/50 border border-gray-200 dark:border-gray-600 rounded-lg text-sm font-medium text-gray-900 dark:text-gray-100 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all duration-200 cursor-pointer"
                  >
                    {THEMES.map(theme => (
                      <option key={theme} value={theme}>
                        {formatThemeName(theme)}
                      </option>
                    ))}
                  </select>
                  <div className="absolute inset-y-0 right-0 flex items-center pr-2 pointer-events-none">
                    <Icon icon="carbon:chevron-down" className="w-4 h-4 text-gray-400 dark:text-gray-500" />
                  </div>
                </div>
              </div>

              <div className="space-y-2">
                <label className="block text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase tracking-wide">
                  Stream Delay
                </label>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    min={4}
                    max={200}
                    step={4}
                    value={streamDelay}
                    onChange={event => setStreamDelay(Number(event.target.value))}
                    className="flex-1 cursor-pointer"
                  />
                  <span className="text-xs font-medium text-gray-600 dark:text-gray-400 w-12 text-right">
                    {streamDelay}
                    ms
                  </span>
                </div>
              </div>

              <div className="space-y-2">
                <label className="block text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase tracking-wide">
                  Chunk Size
                </label>
                <div className="flex items-center gap-3">
                  <input
                    type="range"
                    min={1}
                    max={16}
                    step={1}
                    value={streamChunkSize}
                    onChange={event => setStreamChunkSize(Number(event.target.value))}
                    className="flex-1 cursor-pointer"
                  />
                  <span className="text-xs font-medium text-gray-600 dark:text-gray-400 w-12 text-right">
                    {normalizedChunkSize}
                  </span>
                </div>
              </div>

              <div className="border-t border-gray-200 dark:border-gray-700" />

              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-gray-600 dark:text-gray-400 uppercase tracking-wide">
                  Dark Mode
                </label>
                <button
                  type="button"
                  className="relative w-12 h-6 rounded-full focus:outline-none focus:ring-2 focus:ring-blue-500/50 hover:shadow-lg active:scale-95 transition-all duration-200 ease-out"
                  style={{
                    backgroundColor: isDark ? '#3b82f6' : '#e5e7eb',
                    transition: 'background-color 0.35s ease-out, box-shadow 0.2s ease, transform 0.1s ease',
                  }}
                  onClick={() => setIsDark(value => !value)}
                >
                  <div
                    className="absolute top-0.5 w-5 h-5 bg-white rounded-full flex items-center justify-center shadow-md"
                    style={{
                      left: isDark ? '26px' : '2px',
                      transform: `scale(${isDark ? 1.02 : 1})`,
                      transition: 'left 0.35s cubic-bezier(0.25, 0.46, 0.45, 0.94), transform 0.2s ease-out, box-shadow 0.2s ease',
                    }}
                  >
                    {isDark
                      ? <Icon icon="carbon:moon" className="w-3 h-3 text-blue-600 drop-shadow-sm" />
                      : <Icon icon="carbon:sun" className="w-3 h-3 text-yellow-500 drop-shadow-sm" />}
                  </div>
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="chatbot-container max-w-5xl w-full bg-white dark:bg-gray-800 rounded-2xl shadow-2xl dark:shadow-gray-900/50 flex flex-col overflow-hidden border border-gray-200 dark:border-gray-700">
          <div className="chatbot-header px-6 py-4 border-b border-gray-200 dark:border-gray-700 bg-gradient-to-r from-blue-50 to-purple-50 dark:from-gray-800 dark:to-gray-800">
            <div className="flex items-center justify-between gap-3">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center shadow-lg">
                  <Icon icon="carbon:chat" className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h1 className="text-lg font-semibold text-gray-800 dark:text-gray-100">
                    markstream-react19
                  </h1>
                  <p className="text-xs text-gray-500 dark:text-gray-400">
                    Streaming markdown demo
                  </p>
                </div>
              </div>

              <div className="flex">
                <a
                  href="https://github.com/Simon-He95/markstream-vue"
                  target="_blank"
                  rel="noreferrer"
                  className="github-star-btn flex items-center gap-2 px-3 py-1.5 bg-gray-800 dark:bg-gray-700 hover:bg-gray-700 dark:hover:bg-gray-600 text-white text-sm font-medium rounded-lg transition-all duration-200 shadow-md hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-blue-500/50"
                >
                  <Icon icon="carbon:star" className="w-4 h-4" />
                  <span>Star</span>
                </a>
                <button
                  type="button"
                  className="ml-2 test-page-btn flex items-center gap-2 px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium rounded-lg transition-all duration-200 shadow-md focus:outline-none focus:ring-2 focus:ring-blue-500/50"
                  title="Go to Test page"
                  onClick={goToTest}
                >
                  <Icon icon="carbon:rocket" className="w-4 h-4" />
                  <span>Test</span>
                </button>
              </div>
            </div>
          </div>

          <main ref={messagesRef} className="chatbot-messages flex-1 overflow-y-auto mr-[1px] mb-4 flex flex-col-reverse">
            <div className="p-6">
              <MemoizedNodeRenderer
                content={content}
                codeBlockDarkTheme={selectedTheme}
                codeBlockLightTheme={selectedTheme}
                themes={themeOptions}
                isDark={isDark}
                customId={PLAYGROUND_CUSTOM_ID}
                deferNodesUntilVisible={false}
                maxLiveNodes={2000}
                liveNodeBuffer={200}
                viewportPriority={false}
              />
            </div>
          </main>
        </div>
      </div>
    </div>
  )
}

// playground-svelte/src/App.svelte
<script lang="ts">
  import MarkdownRender, {
    disableKatex,
    disableMermaid,
    enableKatex,
    enableMermaid,
    MarkdownCodeBlockNode,
    preloadCodeBlockRuntime,
    setCustomComponents,
    setKaTeXWorker,
    setMermaidWorker,
  } from 'markstream-svelte'
  import KatexWorker from 'markstream-svelte/workers/katexRenderer.worker?worker&inline'
  import MermaidWorker from 'markstream-svelte/workers/mermaidParser.worker?worker&inline'
  import { onDestroy, onMount, tick } from 'svelte'
  import { streamContent } from '../../playground/src/const/markdown'
  import { TEST_LAB_SAMPLES } from '../../playground-shared/testLabFixtures'
  import ThinkingNode from './components/ThinkingNode.svelte'

  const PLAYGROUND_CUSTOM_ID = 'playground-demo'
  const PLAYGROUND_CUSTOM_HTML_TAGS = ['thinking'] as const
  const themes = [
    'andromeeda',
    'aurora-x',
    'ayu-dark',
    'catppuccin-frappe',
    'catppuccin-latte',
    'catppuccin-macchiato',
    'catppuccin-mocha',
    'dark-plus',
    'dracula',
    'github-dark',
    'github-light',
    'gruvbox-dark-medium',
    'gruvbox-light-medium',
    'material-theme',
    'min-dark',
    'min-light',
    'monokai',
    'night-owl',
    'one-dark-pro',
    'one-light',
    'rose-pine',
    'rose-pine-dawn',
    'tokyo-night',
    'vitesse-dark',
    'vitesse-light',
  ]

  const diffHideUnchangedRegions = {
    enabled: true,
    contextLineCount: 2,
    minimumLineCount: 4,
    revealLineCount: 5,
  } as const
  const playgroundMonacoOptions = {
    renderSideBySide: false,
    useInlineViewWhenSpaceIsLimited: true,
    maxComputationTime: 0,
    ignoreTrimWhitespace: false,
    renderIndicators: true,
    diffAlgorithm: 'legacy',
    diffHideUnchangedRegions,
    hideUnchangedRegions: diffHideUnchangedRegions,
  } as const

  setKaTeXWorker(new KatexWorker())
  setMermaidWorker(new MermaidWorker())
  if (typeof window !== 'undefined')
    void preloadCodeBlockRuntime()
  setCustomComponents(PLAYGROUND_CUSTOM_ID, {
    thinking: ThinkingNode,
  })

  let currentPath = normalizePath(window.location.pathname)
  let content = ''
  let isDark = window.localStorage.getItem('vueuse-color-scheme') === 'dark'
    || (window.localStorage.getItem('vueuse-color-scheme') == null && window.matchMedia?.('(prefers-color-scheme: dark)').matches)
  let selectedTheme = window.localStorage.getItem('vmr-settings-selected-theme') || 'vitesse-dark'
  let chunkSizeMin = Number(window.localStorage.getItem('vmr-settings-stream-chunk-size-min') || 2)
  let chunkSizeMax = Number(window.localStorage.getItem('vmr-settings-stream-chunk-size-max') || 7)
  let chunkDelayMin = Number(window.localStorage.getItem('vmr-settings-stream-delay-min') || 14)
  let chunkDelayMax = Number(window.localStorage.getItem('vmr-settings-stream-delay-max') || 34)
  let burstiness = Number(window.localStorage.getItem('vmr-settings-stream-burstiness') || 35)
  let isStreaming = false
  let isPaused = false
  let timer: number | null = null
  let cursor = 0
  let sampleId = window.localStorage.getItem('vmr-test-sample') || TEST_LAB_SAMPLES[0].id
  let testInput = (TEST_LAB_SAMPLES.find(sample => sample.id === sampleId) || TEST_LAB_SAMPLES[0]).content
  let testStreamContent = ''
  let testCursor = 0
  let testTimer: number | null = null
  let isTestStreaming = false
  let isTestPaused = false
  let renderMode = (window.localStorage.getItem('vmr-test-render-mode') || 'monaco') as 'monaco' | 'markdown' | 'pre'
  let codeBlockStream = window.localStorage.getItem('vmr-test-code-stream') !== 'false'
  let viewportPriority = window.localStorage.getItem('vmr-test-viewport-priority') !== 'false'
  let batchRendering = window.localStorage.getItem('vmr-test-batch-rendering') !== 'false'
  let typewriter = window.localStorage.getItem('vmr-test-typewriter') !== 'false'
  let mathEnabled = window.localStorage.getItem('vmr-test-math-enabled') !== 'false'
  let mermaidEnabled = window.localStorage.getItem('vmr-test-mermaid-enabled') !== 'false'
  let messagesContainer: HTMLElement | null = null
  let roContainer: ResizeObserver | null = null
  let roContent: ResizeObserver | null = null
  let moMessages: MutationObserver | null = null
  let minHeightCheckScheduled = false
  let minHeightDisabled = false
  let overflowConfirmations = 0
  let clearConfirmations = 0
  let previousContentLength = 0
  let homepagePinnedToBottom = true
  let homepageProgrammaticScroll = false
  let homepageAutoScrollFrame: number | null = null
  let homepageAutoScrollFollowupFrame: number | null = null
  const markdownModeComponents = { code_block: MarkdownCodeBlockNode }
  $: activeSample = TEST_LAB_SAMPLES.find(sample => sample.id === sampleId) || TEST_LAB_SAMPLES[0]
  $: testPreviewContent = isTestStreaming ? testStreamContent : testInput
  $: testStreamProgress = testInput.length ? Math.min(100, Math.round((testPreviewContent.length / testInput.length) * 100)) : 0
  $: document.documentElement.classList.toggle('dark', isDark)
  $: window.localStorage.setItem('vueuse-color-scheme', isDark ? 'dark' : 'light')
  $: window.localStorage.setItem('vmr-settings-selected-theme', selectedTheme)
  $: window.localStorage.setItem('vmr-test-render-mode', renderMode)
  $: window.localStorage.setItem('vmr-test-code-stream', String(codeBlockStream))
  $: window.localStorage.setItem('vmr-test-viewport-priority', String(viewportPriority))
  $: window.localStorage.setItem('vmr-test-batch-rendering', String(batchRendering))
  $: window.localStorage.setItem('vmr-test-typewriter', String(typewriter))
  $: window.localStorage.setItem('vmr-test-math-enabled', String(mathEnabled))
  $: window.localStorage.setItem('vmr-test-mermaid-enabled', String(mermaidEnabled))
  $: mathEnabled ? enableKatex() : disableKatex()
  $: mermaidEnabled ? enableMermaid() : disableMermaid()
  $: streamChunkRangeLabel = Math.min(chunkSizeMin, chunkSizeMax) + '-' + Math.max(chunkSizeMin, chunkSizeMax)
  $: streamDelayRangeLabel = Math.min(chunkDelayMin, chunkDelayMax) + '-' + Math.max(chunkDelayMin, chunkDelayMax) + 'ms'
  $: currentTitle = currentPath === '/test' ? 'markstream-svelte test lab' : 'markstream-svelte'
  $: renderModeLabel = renderMode === 'markdown' ? 'MarkdownCodeBlock' : renderMode === 'pre' ? 'PreCodeNode' : 'Monaco'
  $: activeRenderModeLabel = currentPath === '/test' ? renderModeLabel : 'Monaco'
  $: if (currentPath !== '/test' && content.length !== previousContentLength) {
    previousContentLength = content.length
    const shouldStickToBottom = homepagePinnedToBottom || isHomepageAtBottom()
    homepagePinnedToBottom = shouldStickToBottom
    tick().then(() => {
      scheduleCheckMinHeight()
      scheduleHomepageAutoScroll(shouldStickToBottom)
    })
  }

  onMount(() => {
    window.addEventListener('popstate', syncPath)
    window.addEventListener('scroll', updateHomepagePinnedState, { passive: true })
    window.addEventListener('wheel', handleHomepageWheel, { passive: true })
    if (currentPath !== '/test') {
      startStream()
      tick().then(observeHomepageMessages)
    }
    return () => {
      window.removeEventListener('popstate', syncPath)
      window.removeEventListener('scroll', updateHomepagePinnedState)
      window.removeEventListener('wheel', handleHomepageWheel)
    }
  })

  onDestroy(() => {
    stopStream()
    stopTestStream()
    disconnectHomepageObservers()
    cancelHomepageAutoScroll()
  })

  function normalizePath(pathname: string) {
    const normalized = pathname.replace(/\/+$/, '')
    return normalized || '/'
  }

  function syncPath() {
    currentPath = normalizePath(window.location.pathname)
    if (currentPath === '/test') {
      stopStream()
      disconnectHomepageObservers()
      cancelHomepageAutoScroll()
    }
    else {
      homepagePinnedToBottom = true
      tick().then(observeHomepageMessages)
    }
    if (currentPath !== '/test' && !isStreaming)
      startStream()
  }

  function navigate(pathname: string) {
    const next = normalizePath(pathname)
    if (next !== normalizePath(window.location.pathname))
      window.history.pushState({}, '', next)
    syncPath()
  }

  function randomBetween(min: number, max: number) {
    const lo = Math.min(min, max)
    const hi = Math.max(min, max)
    return Math.round(lo + Math.random() * (hi - lo))
  }

  function startStream() {
    stopStream()
    resetHomepageMinHeightState()
    cancelHomepageAutoScroll()
    homepagePinnedToBottom = true
    content = ''
    cursor = 0
    isPaused = false
    isStreaming = true
    scheduleNextChunk()
    tick().then(observeHomepageMessages)
  }

  function stopStream() {
    if (timer != null)
      window.clearTimeout(timer)
    timer = null
    isStreaming = false
  }

  function stopTestStream() {
    if (testTimer != null)
      window.clearTimeout(testTimer)
    testTimer = null
    isTestStreaming = false
    isTestPaused = false
  }

  function scheduleNextChunk() {
    if (!isStreaming || isPaused)
      return
    if (cursor >= streamContent.length) {
      isStreaming = false
      timer = null
      return
    }
    const burst = Math.random() < burstiness / 100 ? 2 : 1
    const size = randomBetween(chunkSizeMin, chunkSizeMax) * burst
    content += streamContent.slice(cursor, cursor + size)
    cursor += size
    timer = window.setTimeout(scheduleNextChunk, randomBetween(chunkDelayMin, chunkDelayMax))
  }

  function togglePause() {
    if (!isStreaming)
      return
    isPaused = !isPaused
    if (!isPaused)
      scheduleNextChunk()
  }

  function applySelectedSample() {
    const nextSample = TEST_LAB_SAMPLES.find(sample => sample.id === sampleId) || TEST_LAB_SAMPLES[0]
    stopTestStream()
    testInput = nextSample.content
    window.localStorage.setItem('vmr-test-sample', sampleId)
  }

  function chooseSample(id: string) {
    sampleId = id
    applySelectedSample()
  }

  function startTestStream() {
    if (isTestStreaming) {
      stopTestStream()
      return
    }
    testStreamContent = ''
    testCursor = 0
    isTestPaused = false
    isTestStreaming = true
    scheduleNextTestChunk()
  }

  function scheduleNextTestChunk() {
    if (!isTestStreaming || isTestPaused)
      return
    if (testCursor >= testInput.length) {
      isTestStreaming = false
      testTimer = null
      return
    }
    const burst = Math.random() < burstiness / 100 ? 2 : 1
    const size = randomBetween(chunkSizeMin, chunkSizeMax) * burst
    testStreamContent += testInput.slice(testCursor, testCursor + size)
    testCursor += size
    testTimer = window.setTimeout(scheduleNextTestChunk, randomBetween(chunkDelayMin, chunkDelayMax))
  }

  function toggleTestPause() {
    if (!isTestStreaming)
      return
    isTestPaused = !isTestPaused
    if (!isTestPaused)
      scheduleNextTestChunk()
  }

  function resetTestInput() {
    stopTestStream()
    testInput = activeSample.content
  }

  function clearTestInput() {
    stopTestStream()
    testInput = ''
  }

  function resetHomepageMinHeightState() {
    minHeightDisabled = false
    overflowConfirmations = 0
    clearConfirmations = 0
    messagesContainer?.classList.remove('disable-min-height')
  }

  function isHomepageAtBottom(threshold = 64) {
    const scrollRoot = document.scrollingElement
    if (!scrollRoot)
      return true
    return scrollRoot.scrollHeight - scrollRoot.clientHeight - scrollRoot.scrollTop <= threshold
  }

  function updateHomepagePinnedState() {
    if (currentPath === '/test')
      return
    if (homepageProgrammaticScroll) {
      if (isHomepageAtBottom(256)) {
        homepagePinnedToBottom = true
        return
      }
      homepageProgrammaticScroll = false
    }
    homepagePinnedToBottom = isHomepageAtBottom()
  }

  function handleHomepageWheel(event: WheelEvent) {
    if (currentPath === '/test' || event.deltaY >= 0)
      return
    homepageProgrammaticScroll = false
    homepagePinnedToBottom = false
    cancelHomepageAutoScroll()
  }

  function applyHomepageAutoScroll() {
    if (!homepagePinnedToBottom || currentPath === '/test')
      return
    const scrollRoot = document.scrollingElement
    if (!scrollRoot)
      return
    homepageProgrammaticScroll = true
    scrollRoot.scrollTop = scrollRoot.scrollHeight
    homepagePinnedToBottom = true
    window.requestAnimationFrame(() => {
      homepageProgrammaticScroll = false
    })
  }

  function cancelHomepageAutoScroll() {
    if (homepageAutoScrollFrame != null)
      window.cancelAnimationFrame(homepageAutoScrollFrame)
    if (homepageAutoScrollFollowupFrame != null)
      window.cancelAnimationFrame(homepageAutoScrollFollowupFrame)
    homepageAutoScrollFrame = null
    homepageAutoScrollFollowupFrame = null
  }

  function scheduleHomepageAutoScroll(shouldStickToBottom: boolean) {
    if (!shouldStickToBottom || currentPath === '/test')
      return
    if (homepageAutoScrollFrame != null || homepageAutoScrollFollowupFrame != null)
      return
    homepageAutoScrollFrame = window.requestAnimationFrame(() => {
      homepageAutoScrollFrame = null
      applyHomepageAutoScroll()
      homepageAutoScrollFollowupFrame = window.requestAnimationFrame(() => {
        homepageAutoScrollFollowupFrame = null
        applyHomepageAutoScroll()
      })
    })
  }

  function disconnectHomepageObservers() {
    roContainer?.disconnect()
    roContent?.disconnect()
    moMessages?.disconnect()
    roContainer = null
    roContent = null
    moMessages = null
    minHeightCheckScheduled = false
  }

  function scheduleCheckMinHeight() {
    if (minHeightCheckScheduled)
      return
    minHeightCheckScheduled = true
    requestAnimationFrame(() => {
      minHeightCheckScheduled = false
      const container = messagesContainer
      if (!container || currentPath === '/test')
        return

      const requiredOverflowConfirmations = 2
      const requiredClearConfirmations = 3
      const hadClass = container.classList.contains('disable-min-height')

      if (minHeightDisabled || hadClass) {
        container.classList.add('disable-min-height')
        const shouldKeep = container.scrollHeight - container.clientHeight > 1
        if (shouldKeep) {
          clearConfirmations = 0
          minHeightDisabled = true
        }
        else {
          clearConfirmations += 1
          if (clearConfirmations >= requiredClearConfirmations) {
            minHeightDisabled = false
            overflowConfirmations = 0
            container.classList.remove('disable-min-height')
          }
        }
        return
      }

      container.classList.add('disable-min-height')
      const hasOverflow = container.scrollHeight - container.clientHeight > 1
      if (hasOverflow)
        overflowConfirmations += 1
      else
        overflowConfirmations = 0

      if (overflowConfirmations >= requiredOverflowConfirmations) {
        minHeightDisabled = true
        clearConfirmations = 0
        disconnectHomepageObservers()
        container.classList.add('disable-min-height')
      }
      else {
        container.classList.remove('disable-min-height')
      }
    })
  }

  function observeHomepageMessages() {
    const container = messagesContainer
    if (!container || currentPath === '/test')
      return

    disconnectHomepageObservers()
    const scheduleLayoutRefresh = () => {
      scheduleCheckMinHeight()
      scheduleHomepageAutoScroll(homepagePinnedToBottom)
    }
    requestAnimationFrame(scheduleLayoutRefresh)

    roContainer = new ResizeObserver(scheduleLayoutRefresh)
    roContainer.observe(container)

    const tryObserveContent = () => {
      const renderer = Array.from(container.children).find(child =>
        (child as HTMLElement).classList?.contains('markdown-renderer'),
      ) as HTMLElement | undefined
      if (!renderer)
        return
      roContent?.disconnect()
      roContent = new ResizeObserver(scheduleLayoutRefresh)
      roContent.observe(renderer)
    }

    tryObserveContent()
    moMessages = new MutationObserver(() => {
      tryObserveContent()
      scheduleLayoutRefresh()
    })
    moMessages.observe(container, { childList: true, subtree: true })
  }
</script>

<div class:dark={isDark} class="playground-root playground-shell">
  <div class="playground-bg">
    <div class="playground-bg__orb playground-bg__orb--1"></div>
    <div class="playground-bg__orb playground-bg__orb--2"></div>
    <div class="playground-bg__orb playground-bg__orb--3"></div>
  </div>

  <aside class="settings-panel settings-sidebar settings-sidebar--docked">
    <div class="settings-sidebar__header">
      <span class="settings-sidebar__title">Controls</span>
    </div>

    <div class="setting-group">
      <label class="setting-label" for="code-theme">Code Theme</label>
      <select id="code-theme" class="setting-select" bind:value={selectedTheme}>
        {#each themes as theme}
          <option value={theme}>{theme}</option>
        {/each}
      </select>
    </div>

    <div class="setting-group">
      <span class="setting-label">Chunk Size</span>
      <div class="setting-slider-row">
        <span class="setting-slider-label">Min</span>
        <input class="setting-slider" type="range" min="1" max="24" bind:value={chunkSizeMin} />
        <span class="setting-slider-value">{Math.min(chunkSizeMin, chunkSizeMax)}</span>
      </div>
      <div class="setting-slider-row">
        <span class="setting-slider-label">Max</span>
        <input class="setting-slider" type="range" min="1" max="24" bind:value={chunkSizeMax} />
        <span class="setting-slider-value">{Math.max(chunkSizeMin, chunkSizeMax)}</span>
      </div>
    </div>

    <div class="setting-group">
      <span class="setting-label">Chunk Delay</span>
      <div class="setting-slider-row">
        <span class="setting-slider-label">Min</span>
        <input class="setting-slider" type="range" min="8" max="240" step="4" bind:value={chunkDelayMin} />
        <span class="setting-slider-value">{Math.min(chunkDelayMin, chunkDelayMax)}ms</span>
      </div>
      <div class="setting-slider-row">
        <span class="setting-slider-label">Max</span>
        <input class="setting-slider" type="range" min="8" max="240" step="4" bind:value={chunkDelayMax} />
        <span class="setting-slider-value">{Math.max(chunkDelayMin, chunkDelayMax)}ms</span>
      </div>
    </div>

    <div class="setting-group">
      <span class="setting-label">Burstiness</span>
      <div class="setting-slider-row">
        <input class="setting-slider" type="range" min="0" max="100" bind:value={burstiness} />
        <span class="setting-slider-value">{burstiness}%</span>
      </div>
      <p class="setting-hint">Window: {streamChunkRangeLabel} chars / {streamDelayRangeLabel}</p>
    </div>

    <div class="settings-divider"></div>

    <div class="setting-row-inline">
      <span class="setting-label">Dark Mode</span>
      <button type="button" class:theme-toggle--dark={isDark} class="theme-toggle" aria-label="Toggle dark mode" onclick={() => (isDark = !isDark)}>
        <span class="theme-toggle__thumb"></span>
      </button>
    </div>
  </aside>

  {#if currentPath === '/test'}
    <main class="chat-shell chat-shell--test">
      <header class="chat-header chat-header--test">
        <div class="chat-header__brand">
          <div class="chat-header__info">
            <h1 class="chat-header__title">{currentTitle}</h1>
            <p class="chat-header__subtitle">Streaming Markdown Renderer</p>
            <div class="chat-header__meta">
              <span class:chat-header__meta-pill--active={isTestStreaming} class="chat-header__meta-pill">{isTestStreaming ? (isTestPaused ? 'Paused' : 'Streaming') : 'Ready'}</span>
              <span class="chat-header__meta-pill">{selectedTheme}</span>
              <span class="chat-header__meta-pill">{activeRenderModeLabel}</span>
            </div>
          </div>
        </div>
        <nav class="chat-header__nav">
          <a href="https://github.com/Simon-He95/markstream-vue" target="_blank" rel="noreferrer" class="nav-btn nav-btn--github">GitHub</a>
          <button type="button" class="nav-btn nav-btn--docs" onclick={() => navigate('/')}>Home</button>
          <button type="button" class="nav-btn nav-btn--test" onclick={() => navigate('/test')}>Test</button>
        </nav>
      </header>
      <section class="test-lab">
        <div class="workspace-card workspace-card--editor">
          <div class="workspace-card__head">
            <div>
              <h2>Markdown 输入</h2>
              <p>{activeSample.summary}</p>
            </div>
            <span class="mini-pill">{renderModeLabel}</span>
          </div>

          <label class="field">
            Sample
            <select bind:value={sampleId} onchange={applySelectedSample}>
              {#each TEST_LAB_SAMPLES as sample}
                <option value={sample.id}>{sample.title}</option>
              {/each}
            </select>
          </label>

          <div class="sample-list">
            {#each TEST_LAB_SAMPLES as sample}
              <button type="button" class:sample-card--active={sample.id === sampleId} class="sample-card" onclick={() => chooseSample(sample.id)}>
                <strong>{sample.title}</strong>
                <span>{sample.summary}</span>
              </button>
            {/each}
          </div>

          <div class="control-grid">
            <label class="field">
              Render
              <select bind:value={renderMode}>
                <option value="monaco">Monaco</option>
                <option value="markdown">MarkdownCodeBlock</option>
                <option value="pre">PreCodeNode</option>
              </select>
            </label>
            <label class="toggle-item"><input type="checkbox" bind:checked={codeBlockStream} /> Code stream</label>
            <label class="toggle-item"><input type="checkbox" bind:checked={viewportPriority} /> viewportPriority</label>
            <label class="toggle-item"><input type="checkbox" bind:checked={batchRendering} /> batchRendering</label>
            <label class="toggle-item"><input type="checkbox" bind:checked={typewriter} /> typewriter</label>
            <label class="toggle-item"><input type="checkbox" bind:checked={mathEnabled} /> KaTeX</label>
            <label class="toggle-item"><input type="checkbox" bind:checked={mermaidEnabled} /> Mermaid</label>
          </div>

          <div class="control-actions">
            <button type="button" class="action-button action-button--primary" onclick={startTestStream}>{isTestStreaming ? '停止流式渲染' : '开始流式渲染'}</button>
            <button type="button" class="action-button" disabled={!isTestStreaming} onclick={toggleTestPause}>{isTestPaused ? '继续流式渲染' : '暂停流式渲染'}</button>
            <button type="button" class="action-button" onclick={resetTestInput}>重置样例</button>
            <button type="button" class="action-button" onclick={clearTestInput}>清空输入</button>
          </div>

          <div class="progress-block">
            <div class="progress-track"><div class="progress-fill" style={`width: ${testStreamProgress}%`}></div></div>
            <div class="progress-meta">
              <span>{testPreviewContent.length} / {testInput.length || 0}</span>
              <span>{isTestStreaming ? 'Streaming' : 'Static preview'}</span>
            </div>
          </div>

          <textarea bind:value={testInput} spellcheck="false"></textarea>
        </div>
        <div class="workspace-card workspace-card--preview">
          <div class="workspace-card__head">
            <div>
              <h2>Preview</h2>
              <p>Svelte renderer output</p>
            </div>
            <span class="mini-pill">{testStreamProgress}%</span>
          </div>
          <div class="preview-surface">
            <MarkdownRender
              content={testPreviewContent}
              final={!isTestStreaming}
              codeBlockStream={codeBlockStream}
              codeBlockDarkTheme={selectedTheme}
              codeBlockLightTheme={selectedTheme}
              codeBlockMonacoOptions={playgroundMonacoOptions}
              renderCodeBlocksAsPre={renderMode === 'pre'}
              customComponents={renderMode === 'markdown' ? markdownModeComponents : undefined}
              {themes}
              {isDark}
              customId={PLAYGROUND_CUSTOM_ID}
              customHtmlTags={PLAYGROUND_CUSTOM_HTML_TAGS}
              deferNodesUntilVisible={!viewportPriority}
              {viewportPriority}
              {batchRendering}
              {typewriter}
              maxLiveNodes={2000}
              liveNodeBuffer={200}
            />
          </div>
        </div>
      </section>
    </main>
  {:else}
    <div class="chat-wrapper chat-wrapper--with-sidebar">
      <div class="chat-container">
        <header class="chat-header">
          <div class="chat-header__brand">
            <div class="chat-header__logo">MS</div>
            <div class="chat-header__info">
              <h1 class="chat-header__title">{currentTitle}</h1>
              <p class="chat-header__subtitle">Streaming Markdown Renderer</p>
              <div class="chat-header__meta">
                <span class:chat-header__meta-pill--active={isStreaming} class="chat-header__meta-pill">{isStreaming ? (isPaused ? 'Paused' : 'Streaming') : 'Ready'}</span>
                <span class="chat-header__meta-pill">{selectedTheme}</span>
              </div>
            </div>
          </div>
          <nav class="chat-header__nav">
            <a href="https://github.com/Simon-He95/markstream-vue" target="_blank" rel="noreferrer" class="nav-btn nav-btn--github">Star</a>
            <a href="https://markstream.simonhe.me/" target="_blank" rel="noreferrer" class="nav-btn nav-btn--docs">Docs</a>
            <button type="button" class="nav-btn nav-btn--stream" disabled={!isStreaming} onclick={togglePause}>{isPaused ? 'Resume' : 'Pause'}</button>
            <button type="button" class="nav-btn nav-btn--test" onclick={() => navigate('/test')}>Test</button>
            <button type="button" class="nav-btn nav-btn--cdn" onclick={startStream}>Replay</button>
          </nav>
        </header>

        <section class="chat-overview">
          <div class="chat-overview__intro">
            <span class="chat-overview__eyebrow">Live Playground</span>
            <p class="chat-overview__summary">Custom min/max window with your own burst profile.</p>
          </div>
          <div class="chat-overview__stats">
            <div class="chat-overview__stat">
              <span class="chat-overview__stat-label">Chunk</span>
              <strong class="chat-overview__stat-value">{streamChunkRangeLabel}</strong>
            </div>
            <div class="chat-overview__stat">
              <span class="chat-overview__stat-label">Delay</span>
              <strong class="chat-overview__stat-value">{streamDelayRangeLabel}</strong>
            </div>
            <div class="chat-overview__stat">
              <span class="chat-overview__stat-label">Transport</span>
              <strong class="chat-overview__stat-value">Scheduler</strong>
            </div>
            <div class="chat-overview__stat">
              <span class="chat-overview__stat-label">Burst</span>
              <strong class="chat-overview__stat-value">{burstiness}%</strong>
            </div>
          </div>
        </section>

        <main bind:this={messagesContainer} class="chat-messages chatbot-messages">
          <MarkdownRender
            className="chat-messages__content"
            {content}
            final={!isStreaming}
            codeBlockStream={true}
            codeBlockDarkTheme={selectedTheme}
            codeBlockLightTheme={selectedTheme}
            codeBlockMonacoOptions={playgroundMonacoOptions}
            renderCodeBlocksAsPre={false}
            customComponents={undefined}
            {themes}
            {isDark}
            customId={PLAYGROUND_CUSTOM_ID}
            customHtmlTags={PLAYGROUND_CUSTOM_HTML_TAGS}
            deferNodesUntilVisible={!viewportPriority}
            {viewportPriority}
            {batchRendering}
            {typewriter}
            maxLiveNodes={2000}
            liveNodeBuffer={200}
          />
        </main>
      </div>
    </div>
  {/if}
</div>
