// packages/markstream-vue2/src/components/ParagraphNode/ParagraphNode.vue
<script setup lang="ts">
import type { ParsedNode } from 'stream-markdown-parser'
import { STANDARD_HTML_TAGS } from 'stream-markdown-parser'
import { computed } from 'vue-demi'
import { getHtmlTagFromContent } from '../../utils/htmlRenderer'
import { getCustomNodeComponents } from '../../utils/nodeComponents'
import CheckboxNode from '../CheckboxNode'
import EmojiNode from '../EmojiNode'
import EmphasisNode from '../EmphasisNode'
import FootnoteAnchorNode from '../FootnoteAnchorNode'
import FootnoteReferenceNode from '../FootnoteReferenceNode'
import HardBreakNode from '../HardBreakNode'
import HighlightNode from '../HighlightNode'
import HtmlBlockNode from '../HtmlBlockNode'
import HtmlInlineNode from '../HtmlInlineNode'
import ImageNode from '../ImageNode'
import InlineCodeNode from '../InlineCodeNode'
import InsertNode from '../InsertNode'
import LinkNode from '../LinkNode'
import { MathInlineNodeAsync } from '../NodeRenderer/asyncComponent'
import ReferenceNode from '../ReferenceNode'
import StrikethroughNode from '../StrikethroughNode'
import StrongNode from '../StrongNode'
import SubscriptNode from '../SubscriptNode'
import SuperscriptNode from '../SuperscriptNode'
import TextNode from '../TextNode'

interface NodeChild {
  type: string
  raw: string
  [key: string]: unknown
}

const props = defineProps<{
  node: {
    type: 'paragraph'
    children: NodeChild[]
    raw: string
  }
  customId?: string
  indexKey?: number | string
  customHtmlTags?: readonly string[]
}>()

const overrides = getCustomNodeComponents(props.customId)

function isWhitespaceText(child: NodeChild) {
  return child.type === 'text' && String((child as any).content ?? '').trim() === ''
}

function getTextContent(child: NodeChild) {
  return String((child as any).content ?? '')
}

function getMeaningfulLinkChildren(child: NodeChild) {
  if (child.type !== 'link' || !Array.isArray((child as any).children))
    return []

  return (child as any).children.filter((linkChild: NodeChild) => !isWhitespaceText(linkChild))
}

function isImageOnlyLink(child: NodeChild) {
  const linkChildren = getMeaningfulLinkChildren(child)
  return linkChildren.length === 1 && linkChildren[0]?.type === 'image'
}

const meaningfulChildren = computed(() => props.node.children.filter(child => !isWhitespaceText(child)))

const isMediaOnlyParagraph = computed(() => (
  meaningfulChildren.value.length > 0
  && meaningfulChildren.value.every(child => child.type === 'image' || isImageOnlyLink(child))
))

const customHtmlTagsSet = computed<Set<string>>(() => {
  const tags = props.customHtmlTags ?? []
  return new Set((tags as string[]).map(t => String(t).trim().toLowerCase()).filter(Boolean))
})

const renderedChildren = computed(() => {
  if (!isMediaOnlyParagraph.value || meaningfulChildren.value.length <= 1)
    return props.node.children

  const children: NodeChild[] = []
  for (let i = 0; i < props.node.children.length; i++) {
    const child = props.node.children[i]
    if (!isWhitespaceText(child)) {
      children.push(child)
      continue
    }

    const hasPrevious = children.length > 0
    const hasNext = props.node.children.slice(i + 1).some(nextChild => !isWhitespaceText(nextChild))
    if (!hasPrevious || !hasNext)
      continue

    children.push({
      ...child,
      content: ' ',
      raw: ' ',
    } as NodeChild)
  }

  return children
})

function getChildProps(child: NodeChild, index: number) {
  return {
    'node': child,
    'index-key': `${props.indexKey ?? 'paragraph'}-${index}`,
    'custom-id': props.customId,
    'custom-html-tags': props.customHtmlTags,
  }
}

const nodeComponents = {
  inline_code: InlineCodeNode,
  image: ImageNode,
  link: LinkNode,
  hardbreak: HardBreakNode,
  emphasis: EmphasisNode,
  strong: StrongNode,
  strikethrough: StrikethroughNode,
  highlight: HighlightNode,
  insert: InsertNode,
  subscript: SubscriptNode,
  superscript: SuperscriptNode,
  html_inline: HtmlInlineNode,
  html_block: HtmlBlockNode,
  emoji: EmojiNode,
  checkbox: CheckboxNode,
  math_inline: MathInlineNodeAsync,
  checkbox_input: CheckboxNode,
  reference: ReferenceNode,
  footnote_anchor: FootnoteAnchorNode,
  footnote_reference: FootnoteReferenceNode,
  text: TextNode,
  ...overrides,
}

// Process children to handle non-whitelisted custom HTML tags
function processChild(child: NodeChild, index: number): { child: NodeChild, component: any } {
  // Handle html_block and html_inline nodes with non-whitelisted custom tags
  if (child.type === 'html_block' || child.type === 'html_inline') {
    const tag = String((child as any).tag ?? '').trim().toLowerCase()
      || getHtmlTagFromContent((child as any).content)

    // Check if there's a registered custom component for this tag
    const hasCustomComponent = (overrides as any)[tag]

    // Only escape if: tag exists, not in whitelist, not standard HTML, AND no custom component registered
    if (tag && !customHtmlTagsSet.value.has(tag) && !STANDARD_HTML_TAGS.has(tag) && !hasCustomComponent) {
      // Non-whitelisted, non-standard HTML tag: render as plain text
      const rawContent = String((child as any).content ?? (child as any).raw ?? '')
      const escapedContent = rawContent
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')

      return {
        child: {
          type: 'text',
          content: escapedContent,
          raw: escapedContent,
        } as NodeChild,
        component: TextNode,
      }
    }
  }

  return { child, component: (nodeComponents as any)[child.type] }
}
</script>

<template>
  <p dir="auto" class="paragraph-node">
    <template
      v-for="(child, index) in renderedChildren"
      :key="`${indexKey || 'paragraph'}-${index}`"
    >
      <template v-if="isMediaOnlyParagraph && isWhitespaceText(child)">
        {{ getTextContent(child) }}
      </template>
      <component
        :is="processChild(child, index).component"
        v-else
        v-bind="getChildProps(processChild(child, index).child, index)"
      />
    </template>
  </p>
</template>

<style scoped>
.paragraph-node{
  margin: 1.25em 0;
}
li .paragraph-node{
  margin: 0;
}
</style>

// packages/markstream-react/src/components/ParagraphNode/ParagraphNode.tsx
import type { ParsedNode } from 'stream-markdown-parser'
import type { NodeComponentProps } from '../../types/node-component'
import React from 'react'
import { getCustomNodeComponents } from '../../customComponents'
import { BLOCK_LEVEL_TYPES, renderNodeChildren } from '../../renderers/renderChildren'
import { isParagraphBreakingCustomHtmlNode } from '../../utils/customHtmlTag'

function isWhitespaceTextNode(node: ParsedNode | null | undefined) {
  return node?.type === 'text' && String((node as any)?.content ?? '').trim() === ''
}

function getMeaningfulLinkChildren(node: ParsedNode | null | undefined) {
  if (node?.type !== 'link' || !Array.isArray((node as any)?.children))
    return []

  return ((node as any).children as ParsedNode[]).filter(child => !isWhitespaceTextNode(child))
}

function isImageOnlyLinkNode(node: ParsedNode | null | undefined) {
  const linkChildren = getMeaningfulLinkChildren(node)
  return linkChildren.length === 1 && linkChildren[0]?.type === 'image'
}

function renderParagraphInlineNodes(
  nodes: ParsedNode[],
  renderNode: NonNullable<NodeComponentProps<{ type: 'paragraph', children?: ParsedNode[] }>['renderNode']>,
  ctx: NonNullable<NodeComponentProps<{ type: 'paragraph', children?: ParsedNode[] }>['ctx']>,
  prefix: string,
) {
  const meaningfulChildren = nodes.filter(child => !isWhitespaceTextNode(child))
  const mediaOnly = meaningfulChildren.length > 0
    && meaningfulChildren.every(child => child.type === 'image' || isImageOnlyLinkNode(child))

  if (!mediaOnly || meaningfulChildren.length <= 1)
    return renderNodeChildren(nodes, ctx, prefix, renderNode)

  const normalizedNodes: ParsedNode[] = []
  for (let index = 0; index < nodes.length; index++) {
    const child = nodes[index]
    if (!isWhitespaceTextNode(child)) {
      normalizedNodes.push(child)
      continue
    }

    const hasPrevious = normalizedNodes.length > 0
    const hasNext = nodes.slice(index + 1).some(nextChild => !isWhitespaceTextNode(nextChild))
    if (!hasPrevious || !hasNext)
      continue

    normalizedNodes.push({
      ...(child as any),
      content: ' ',
      raw: ' ',
    })
  }

  return normalizedNodes.map((child, index) => (
    mediaOnly && isWhitespaceTextNode(child)
      ? <React.Fragment key={`${prefix}-${index}`}>{String((child as any)?.content ?? '')}</React.Fragment>
      : renderNode(child, `${prefix}-${index}`, ctx)
  ))
}

export function ParagraphNode(props: NodeComponentProps<{ type: 'paragraph', children?: ParsedNode[] }>) {
  const { node, ctx, renderNode, indexKey, children } = props
  if (!ctx || !renderNode) {
    return (
      <p dir="auto" className="paragraph-node">
        {children}
      </p>
    )
  }

  const nodeChildren = node.children ?? []
  const customComponents = ctx.customComponents ?? getCustomNodeComponents(ctx.customId)
  const displayComponents = {
    ...customComponents,
    ...(ctx.htmlComponents ?? {}),
    ...(ctx.streamingComponents ?? {}),
  }
  const parts: React.ReactNode[] = []
  const inlineBuffer: ParsedNode[] = []

  const flushInline = () => {
    if (!inlineBuffer.length)
      return
    const chunkIndex = parts.length
    parts.push(
      <p key={`${String(indexKey ?? 'paragraph')}-inline-${chunkIndex}`} dir="auto" className="paragraph-node">
        {renderParagraphInlineNodes(inlineBuffer.slice(), renderNode, ctx, `${String(indexKey ?? 'paragraph')}-${chunkIndex}`)}
      </p>,
    )
    inlineBuffer.length = 0
  }

  nodeChildren.forEach((child, childIndex) => {
    const canUseHtmlDisplayMetadata = (ctx.htmlPolicy ?? 'safe') !== 'escape'
      || (child.type !== 'html_inline' && child.type !== 'html_block')
    if (BLOCK_LEVEL_TYPES.has(child.type) || (canUseHtmlDisplayMetadata && isParagraphBreakingCustomHtmlNode(child, displayComponents, ctx.customHtmlTags))) {
      flushInline()
      parts.push(
        <React.Fragment key={`${String(indexKey ?? 'paragraph')}-block-${childIndex}`}>
          {renderNode(child, `${String(indexKey ?? 'paragraph')}-block-${childIndex}`, ctx)}
        </React.Fragment>,
      )
    }
    else {
      inlineBuffer.push(child)
    }
  })
  flushInline()

  if (!parts.length) {
    return (
      <p dir="auto" className="paragraph-node">
        {renderParagraphInlineNodes(nodeChildren, renderNode, ctx, String(indexKey ?? 'paragraph'))}
      </p>
    )
  }

  return <>{parts}</>
}

export default ParagraphNode
