// packages/markstream-vue2/src/components/HtmlBlockNode/HtmlBlockNode.vue
<script setup lang="ts">
import type { HtmlPolicy } from 'stream-markdown-parser'
import { isHtmlTagBlocked, NON_STRUCTURING_HTML_TAGS, sanitizeHtmlContent, sanitizeHtmlTokenAttrs, tokenAttrsToRecord } from 'stream-markdown-parser'
import { computed, defineComponent, inject, onBeforeUnmount, ref, watch } from 'vue-demi'
import { useViewportPriority } from '../../composables/viewportPriority'
import { hasCustomComponents, parseHtmlToVNodes } from '../../utils/htmlRenderer'
import { renderMarkdownNodesToHtml } from '../../utils/nestedHtml'
import { getCustomNodeComponents } from '../../utils/nodeComponents'

const props = defineProps<{
  node: {
    content: string
    raw?: string
    tag?: string
    attrs?: [string, string][] | null
    children?: any[]
    loading?: boolean
  }
  customId?: string
  htmlPolicy?: HtmlPolicy
}>()

const inheritedHtmlPolicy = inject<{ value?: HtmlPolicy } | undefined>('markstreamHtmlPolicy', undefined)
const resolvedHtmlPolicy = computed<HtmlPolicy>(() => props.htmlPolicy ?? inheritedHtmlPolicy?.value ?? 'safe')

const boundAttrs = computed(() => {
  const sanitizedAttrs = sanitizeHtmlTokenAttrs(props.node.attrs, resolvedHtmlPolicy.value)
  if (!sanitizedAttrs)
    return undefined
  const record = tokenAttrsToRecord(sanitizedAttrs)
  return Object.keys(record).length > 0 ? record : undefined
})

// Get custom components from global registry
const customComponents = computed(() => {
  return getCustomNodeComponents(props.customId)
})

// Dynamic wrapper component for rendering VNodes
const DynamicRenderer = defineComponent({
  name: 'DynamicRenderer',
  props: {
    content: {
      type: String,
      required: true,
    },
    customComponents: {
      type: Object as () => Record<string, any>,
      required: true,
    },
    htmlPolicy: {
      type: String as () => HtmlPolicy,
      default: 'safe',
    },
  },
  render() {
    const nodes = parseHtmlToVNodes(this.content, this.customComponents, undefined, this.htmlPolicy)
    return (nodes || []) as any
  },
})

const structuredChildren = computed(() => Array.isArray(props.node.children) ? props.node.children : [])
const structuredTag = computed(() => String(props.node.tag || 'div'))
const isBlockedStructuredTag = computed(() => {
  const tag = structuredTag.value.trim().toLowerCase()
  return NON_STRUCTURING_HTML_TAGS.has(tag) || isHtmlTagBlocked(tag, resolvedHtmlPolicy.value)
})
const structuredHtml = computed(() => {
  if (structuredChildren.value.length === 0 || !props.node.tag || isBlockedStructuredTag.value)
    return ''
  return renderMarkdownNodesToHtml(structuredChildren.value as any, { htmlPolicy: resolvedHtmlPolicy.value })
})

// Computed property to determine render mode and content
const renderMode = computed(() => {
  if (structuredChildren.value.length > 0 && !!props.node.tag && !isBlockedStructuredTag.value)
    return { mode: 'structured' as const }

  const content = props.node.content
  if (!content)
    return { mode: 'html', content: '' }

  if (resolvedHtmlPolicy.value === 'escape')
    return { mode: 'html', content: sanitizeHtmlContent(content, resolvedHtmlPolicy.value) }

  // Check if content contains custom components
  if (!hasCustomComponents(content, customComponents.value))
    return { mode: 'html', content: sanitizeHtmlContent(content, resolvedHtmlPolicy.value) }

  return { mode: 'dynamic', content }
})

const htmlRef = ref<HTMLElement | null>(null)
const shouldRender = ref(typeof window === 'undefined')
const renderContent = ref(props.node.content)
const registerVisibility = useViewportPriority()
let visibilityHandle: ReturnType<typeof registerVisibility> | null = null
const isDeferred = !!props.node.loading

if (typeof window !== 'undefined') {
  watch(
    htmlRef,
    (el) => {
      visibilityHandle?.destroy?.()
      visibilityHandle = null
      if (!isDeferred) {
        shouldRender.value = true
        renderContent.value = props.node.content
        return
      }
      if (!el) {
        shouldRender.value = false
        return
      }
      const handle = registerVisibility(el, { rootMargin: '400px' })
      visibilityHandle = handle
      shouldRender.value = handle.isVisible.value
      handle.whenVisible.then(() => {
        shouldRender.value = true
      })
    },
    { immediate: true },
  )

  watch(
    () => props.node.content,
    (val) => {
      if (!isDeferred || shouldRender.value) {
        renderContent.value = val
      }
    },
  )
}
else {
  shouldRender.value = true
}

onBeforeUnmount(() => {
  visibilityHandle?.destroy?.()
  visibilityHandle = null
})
</script>

<template>
  <!-- eslint-disable vue/no-v-text-v-html-on-component -->
  <component
    :is="structuredTag"
    v-if="renderMode.mode === 'structured' && shouldRender"
    ref="htmlRef"
    class="html-block-node"
    v-bind="boundAttrs"
    v-html="structuredHtml"
  />
  <!-- eslint-enable vue/no-v-text-v-html-on-component -->
  <component
    :is="structuredTag"
    v-else-if="renderMode.mode === 'structured'"
    ref="htmlRef"
    class="html-block-node"
    v-bind="boundAttrs"
  >
    <div class="html-block-node__placeholder">
      <slot name="placeholder" :node="node">
        <span class="html-block-node__placeholder-bar" />
        <span class="html-block-node__placeholder-bar w-4/5" />
        <span class="html-block-node__placeholder-bar w-2/3" />
      </slot>
    </div>
  </component>
  <div
    v-else
    ref="htmlRef"
    class="html-block-node"
  >
    <template v-if="shouldRender">
      <!-- Use dynamic rendering for custom components -->
      <DynamicRenderer v-if="renderMode.mode === 'dynamic'" :content="renderMode.content" :custom-components="customComponents" :html-policy="resolvedHtmlPolicy" />
      <!-- Fallback to v-html for standard HTML -->
      <div v-else v-bind="boundAttrs" v-html="renderMode.content" />
    </template>
    <div v-else class="html-block-node__placeholder">
      <slot name="placeholder" :node="node">
        <span class="html-block-node__placeholder-bar" />
        <span class="html-block-node__placeholder-bar w-4/5" />
        <span class="html-block-node__placeholder-bar w-2/3" />
      </slot>
    </div>
  </div>
</template>

<style scoped>
.html-block-node__placeholder {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  padding: 0.5rem 0;
}
.html-block-node__placeholder-bar {
  display: block;
  height: 0.8rem;
  border-radius: 9999px;
  background-image: linear-gradient(90deg, rgba(148, 163, 184, 0.35), rgba(148, 163, 184, 0.1), rgba(148, 163, 184, 0.35));
  background-size: 200% 100%;
  animation: html-block-node-shimmer 1.2s ease infinite;
}

@keyframes html-block-node-shimmer {
  0% {
    background-position: 0% 0%;
  }
  100% {
    background-position: 200% 0%;
  }
}
</style>

// packages/markstream-react/src/components/HtmlBlockNode/HtmlBlockNode.tsx
import type { HtmlPolicy, ParsedNode } from 'stream-markdown-parser'
import type { CustomComponentMap } from '../../customComponents'
import type { NodeComponentProps } from '../../types/node-component'
import React, { useEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react'
import { isHtmlTagBlocked, NON_STRUCTURING_HTML_TAGS, sanitizeHtmlContent, sanitizeHtmlTokenAttrs } from 'stream-markdown-parser'
import { useViewportPriority } from '../../context/viewportPriority'
import { getCustomComponentsRevision, getCustomNodeComponents, subscribeCustomComponents } from '../../customComponents'
import { renderNodeChildren, tokenAttrsToProps } from '../../renderers/renderChildren'
import { hasCustomHtmlComponents, normalizeDomAttrs, parseHtmlToReactNodes } from '../../utils/htmlToReact'

function mergeHtmlBlockClassName(attrs?: Record<string, any>) {
  const next = { ...(attrs || {}) }
  const existing = typeof next.className === 'string' ? next.className.trim() : ''
  next.className = existing ? `html-block-node ${existing}` : 'html-block-node'
  return next
}

export function HtmlBlockNode(props: NodeComponentProps<{
  type: 'html_block'
  content: string
  raw?: string
  tag?: string
  attrs?: [string, string | null][] | null
  children?: ParsedNode[]
  loading?: boolean
}> & {
  customComponents?: CustomComponentMap
  htmlPolicy?: HtmlPolicy
  placeholder?: React.ReactNode
}) {
  const { node, placeholder, customId } = props
  const htmlPolicy = props.htmlPolicy ?? props.ctx?.htmlPolicy ?? 'safe'
  const registerViewport = useViewportPriority()
  const [hostEl, setHostEl] = useState<HTMLElement | null>(null)
  const handleRef = useRef<ReturnType<typeof registerViewport> | null>(null)
  const [shouldRender, setShouldRender] = useState(() => typeof window === 'undefined')
  const [renderContent, setRenderContent] = useState(node.content)
  const isDeferred = Boolean(node.loading)

  const customComponentsRevision = useSyncExternalStore(
    subscribeCustomComponents,
    getCustomComponentsRevision,
    getCustomComponentsRevision,
  )

  const effectiveCustomComponents = useMemo(() => {
    const legacyComponents = props.customComponents
      ?? props.ctx?.customComponents
      ?? getCustomNodeComponents(customId)
    return {
      ...legacyComponents,
      ...(props.ctx?.htmlComponents ?? {}),
    }
  }, [
    customId,
    props.ctx?.customComponents,
    props.ctx?.htmlComponents,
    props.customComponents,
    customComponentsRevision,
  ])

  useEffect(() => {
    if (typeof window === 'undefined') {
      setShouldRender(true)
      return
    }
    handleRef.current?.destroy()
    handleRef.current = null
    if (!isDeferred) {
      setShouldRender(true)
      setRenderContent(node.content)
      return
    }
    if (!hostEl) {
      setShouldRender(false)
      return
    }
    const handle = registerViewport(hostEl, { rootMargin: '400px' })
    handleRef.current = handle
    if (handle.isVisible())
      setShouldRender(true)
    handle.whenVisible.then(() => setShouldRender(true)).catch(() => {})
    return () => {
      handle.destroy()
      handleRef.current = null
    }
  }, [hostEl, isDeferred, node.content, registerViewport])

  useEffect(() => () => {
    handleRef.current?.destroy()
    handleRef.current = null
  }, [])

  useEffect(() => {
    if (!isDeferred || shouldRender)
      setRenderContent(node.content)
  }, [isDeferred, node.content, shouldRender])

  const boundAttrs = useMemo(() => {
    const rawAttrs = tokenAttrsToProps(sanitizeHtmlTokenAttrs(node.attrs ?? undefined, htmlPolicy))
    return rawAttrs ? normalizeDomAttrs(rawAttrs as Record<string, string>) : undefined
  }, [htmlPolicy, node.attrs])
  const structuredTag = useMemo(() => String(node.tag ?? '').trim(), [node.tag])
  const structuredBoundAttrs = useMemo(() => {
    const rawAttrs = tokenAttrsToProps(sanitizeHtmlTokenAttrs(node.attrs ?? undefined, htmlPolicy, structuredTag))
    return rawAttrs ? normalizeDomAttrs(rawAttrs as Record<string, string>) : undefined
  }, [htmlPolicy, node.attrs, structuredTag])
  const structuredChildren = useMemo(() => Array.isArray(node.children) ? node.children : [], [node.children])
  const isStructured = structuredChildren.length > 0
    && !!structuredTag
    && !NON_STRUCTURING_HTML_TAGS.has(structuredTag.toLowerCase())
    && !isHtmlTagBlocked(structuredTag, htmlPolicy)
    && !!props.ctx
    && !!props.renderNode
  const structuredWrapperProps = useMemo(
    () => mergeHtmlBlockClassName(structuredBoundAttrs as Record<string, any> | undefined),
    [structuredBoundAttrs],
  )

  // Check if we should use dynamic rendering
  const useDynamic = useMemo(() => {
    if (htmlPolicy === 'escape')
      return false
    return hasCustomHtmlComponents(node.content ?? '', effectiveCustomComponents)
  }, [effectiveCustomComponents, htmlPolicy, node.content])

  const reactNodes = useMemo(() => {
    if (!useDynamic || !node.content)
      return null
    return parseHtmlToReactNodes(node.content, effectiveCustomComponents, htmlPolicy)
  }, [effectiveCustomComponents, htmlPolicy, node.content, useDynamic])
  const safeHtmlContent = useMemo(() => sanitizeHtmlContent(renderContent ?? '', htmlPolicy), [htmlPolicy, renderContent])
  const structuredContent = useMemo(() => {
    if (!isStructured || !props.ctx || !props.renderNode)
      return null
    return renderNodeChildren(
      structuredChildren,
      props.ctx,
      `${String(props.indexKey ?? 'html-block')}-structured`,
      props.renderNode,
    )
  }, [isStructured, props.ctx, props.indexKey, props.renderNode, structuredChildren])

  const placeholderNode = (
    <div className="html-block-node__placeholder">
      {placeholder ?? (
        <>
          <span className="html-block-node__placeholder-bar" />
          <span className="html-block-node__placeholder-bar w-4/5" />
          <span className="html-block-node__placeholder-bar w-2/3" />
        </>
      )}
    </div>
  )

  if (isStructured) {
    return React.createElement(
      structuredTag,
      {
        ...(structuredWrapperProps as any),
        ref: setHostEl,
      },
      shouldRender ? structuredContent : placeholderNode,
    )
  }

  return (
    <div ref={setHostEl} className="html-block-node" {...(boundAttrs as any)}>
      {shouldRender
        ? (
            useDynamic && reactNodes
              ? (
                  <>{reactNodes}</>
                )
              : (
                  <div dangerouslySetInnerHTML={{ __html: safeHtmlContent }} />
                )
          )
        : placeholderNode}
    </div>
  )
}

export default HtmlBlockNode
