// src/components/InlineCodeNode/InlineCodeNode.vue
<script setup lang="ts">
defineProps<{
  node: {
    type: 'inline_code'
    code: string
    raw: string
  }
}>()
</script>

<template>
  <code
    class="inline px-1 py-0.5 rounded text-xs font-mono bg-secondary whitespace-normal break-words max-w-full before:content-[''] after:content-['']"
  >{{ node.code }}</code>
</template>

// packages/markstream-react/src/components/InlineCodeNode/InlineCodeNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import React from 'react'

export function InlineCodeNode(props: NodeComponentProps<{ type: 'inline_code', code: string }>) {
  const { node } = props
  return (
    <code className="inline-code inline text-[85%] px-1 py-0.5 rounded font-mono bg-[hsl(var(--secondary))] whitespace-normal break-words max-w-full">
      {node.code}
    </code>
  )
}

export default InlineCodeNode
