// packages/markstream-svelte/src/components/FootnoteReferenceNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { getString } from './shared/node-helpers'

  export let node: SvelteRenderableNode

  $: id = getString((node as any)?.id)
  $: href = id ? `#fnref--${id}` : undefined
  $: linkAttrs = href ? { href } : {}

  function scrollToFootnote(event: MouseEvent) {
    event.preventDefault()
    if (typeof document === 'undefined' || !id)
      return
    const target = document.querySelector(href || '')
    target?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<sup id={id ? `fnref-${id}` : undefined} class="footnote-reference" onclick={scrollToFootnote}>
  <span {...linkAttrs} title={id ? `查看脚注 ${id}` : undefined} class="footnote-link cursor-pointer">
    [{id}]
  </span>
</sup>

// src/components/FootnoteReferenceNode/FootnoteReferenceNode.vue
<script setup lang="ts">
// 定义脚注引用节点
interface FootnoteReferenceNode {
  type: 'footnote_reference'
  id: string
  raw: string
}

// 接收props
const props = defineProps<{
  node: FootnoteReferenceNode
}>()
const href = `#footnote-${props.node.id}`
function handleScroll() {
  if (typeof document === 'undefined') {
    // SSR: nothing to do
    return
  }
  const element = document.querySelector(href)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' })
  }
  else {
    console.warn(`Element with href: ${href} not found`)
  }
}
</script>

<template>
  <sup class="footnote-reference" :id="`fnref-${node.id}`" @click="handleScroll">
    <span
      :href="href"
      :title="`查看脚注 ${node.id}`"
      class="footnote-link cursor-pointer"
    >[{{ node.id }}]</span>
  </sup>
</template>

<style scoped>
.footnote-reference {
  font-size: 0.75em;
  line-height: 0;
}

.footnote-link {
  color: #0366d6;
  text-decoration: none;
}

.footnote-link:hover {
  text-decoration: underline;
}
</style>
