// src/components/MarkdownCodeBlockNode/MarkdownCodeBlockNode.vue
<script setup lang="ts">
import type { MarkdownCodeBlockPreviewPayload, ShikiCodeBlockProps } from '../../types/component-props'
import type { RegisterHighlightOptions, ShikiRendererOptions } from '../../utils/shikiLanguage'
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useSafeI18n } from '../../composables/useSafeI18n'
import { hideTooltip, showTooltipForAnchor } from '../../composables/useSingletonTooltip'
import { useViewportPriority } from '../../composables/viewportPriority'
import {
  getLanguageIcon,
  languageIconsRevision,
  languageMap,
} from '../../utils/languageIcon'
import {
  createRegisteredHighlightLanguages,
  getEffectiveRegisterHighlightOptions,
  getEffectiveShikiRendererOptions,
  getHighlightRegistrationKey,
  getShikiLanguageMatchKey,
  normalizeDisplayLanguage,
  normalizeShikiLanguage,
  registerHighlightOnce,
} from '../../utils/shikiLanguage'
import CodeBlockShell from '../CodeBlockNode/CodeBlockShell.vue'

interface MarkdownCodeBlockNodeProps extends ShikiCodeBlockProps {
  node: {
    type: 'code_block'
    language: string
    code: string
    raw: string
    diff?: boolean
    originalCode?: string
    updatedCode?: string
  }
  loading?: boolean
  stream?: boolean
  darkTheme?: string
  lightTheme?: string
  isDark?: boolean
  isShowPreview?: boolean
  enableFontSizeControl?: boolean
  minWidth?: string | number
  maxWidth?: string | number
  showPreviewButton?: boolean
  showCollapseButton?: boolean
  showFontSizeButtons?: boolean
  showTooltips?: boolean
  autoScrollOnUpdate?: boolean
  autoScrollInitial?: boolean
  estimatedHeightPx?: number
  estimatedContentHeightPx?: number
}

const props = withDefaults(
  defineProps<MarkdownCodeBlockNodeProps>(),
  {
    isShowPreview: true,
    // Align defaults with CodeBlockNode behaviour: light first, explicit dark
    darkTheme: 'vitesse-dark',
    lightTheme: 'vitesse-light',
    isDark: false,
    loading: true,
    stream: true,
    enableFontSizeControl: true,
    minWidth: undefined,
    maxWidth: undefined,
    // Header configuration: allow consumers to toggle built-in buttons and header visibility
    showHeader: true,
    showCopyButton: true,
    showExpandButton: true,
    showPreviewButton: true,
    showCollapseButton: true,
    showFontSizeButtons: true,
    autoScrollOnUpdate: true,
    autoScrollInitial: true,
  },
)

const emits = defineEmits<{
  (e: 'previewCode', payload: MarkdownCodeBlockPreviewPayload): void
  (e: 'copy', code: string): void
}>()
const { t } = useSafeI18n()

const codeLanguage = ref<string>(normalizeDisplayLanguage(props.node.language))
const copyText = ref(false)
const isExpanded = ref(false)
const isCollapsed = ref(false)
const container = ref<HTMLElement | null>(null)
const codeBlockContent = ref<HTMLElement | null>(null)
const rendererTarget = ref<HTMLElement | null>(null)
const fallbackHtml = ref('')
const rendererReady = ref(false)
let renderObserver: MutationObserver | undefined
const registerVisibility = useViewportPriority()
const viewportHandle = ref<ReturnType<typeof registerVisibility> | null>(null)
const viewportReady = ref(typeof window === 'undefined')

if (typeof window !== 'undefined') {
  watch(
    () => container.value,
    (el) => {
      viewportHandle.value?.destroy()
      viewportHandle.value = null
      if (!el) {
        viewportReady.value = false
        return
      }
      const handle = registerVisibility(el, { rootMargin: '400px' })
      viewportHandle.value = handle
      viewportReady.value = handle.isVisible.value
      handle.whenVisible.then(() => {
        viewportReady.value = true
      })
    },
    { immediate: true },
  )
}

// Auto-scroll state management
const autoScrollEnabled = ref(props.autoScrollInitial !== false)
const lastScrollTop = ref(0) // Track last scroll position to detect scroll direction
const shouldAutoScrollOnUpdate = computed(() => props.autoScrollOnUpdate !== false)

// Font size control
const codeFontMin = 10
const codeFontMax = 36
const codeFontStep = 1
const defaultCodeFontSize = ref<number>(14)
const codeFontSize = ref<number>(defaultCodeFontSize.value)

const fontBaselineReady = computed(() => {
  const a = defaultCodeFontSize.value
  const b = codeFontSize.value
  return typeof a === 'number' && Number.isFinite(a) && a > 0 && typeof b === 'number' && Number.isFinite(b) && b > 0
})

// 计算用于显示的语言名称
const displayLanguage = computed(() => {
  const lang = codeLanguage.value.trim().toLowerCase()
  return languageMap[lang] || lang.charAt(0).toUpperCase() + lang.slice(1)
})

// Computed property for language icon
const languageIcon = computed(() => {
  void languageIconsRevision.value
  const lang = codeLanguage.value.trim().toLowerCase()
  return getLanguageIcon(lang.split(':')[0])
})

// Check if the language is previewable (HTML or SVG)
const isPreviewable = computed(() => {
  const lang = codeLanguage.value.trim().toLowerCase()
  return props.isShowPreview && (lang === 'html' || lang === 'svg')
})

// Compute inline style for container to respect optional min/max width
const containerStyle = computed(() => {
  const s: Record<string, string> = {}
  const fmt = (v: string | number | undefined) => {
    if (v == null)
      return undefined
    return typeof v === 'number' ? `${v}px` : String(v)
  }
  const min = fmt(props.minWidth)
  const max = fmt(props.maxWidth)
  if (min)
    s.minWidth = min
  if (max)
    s.maxWidth = max
  return s
})
const estimatedVisibleContentHeight = computed(() => {
  const value = props.estimatedContentHeightPx
  return typeof value === 'number' && Number.isFinite(value) && value > 0
    ? Math.round(value)
    : null
})

const shouldReserveEstimatedContentHeight = computed(() => {
  return estimatedVisibleContentHeight.value != null && !rendererReady.value
})

// Computed style for code block content with font size
const contentStyle = computed(() => {
  return {
    fontSize: `${codeFontSize.value}px`,
    ...(shouldReserveEstimatedContentHeight.value
      ? { minHeight: `${estimatedVisibleContentHeight.value}px` }
      : {}),
  }
})
const tooltipsEnabled = computed(() => props.showTooltips !== false)

function getPreferredColorScheme() {
  return props.isDark ? props.darkTheme : props.lightTheme
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function renderFallback(code: string) {
  renderObserver?.disconnect()
  renderObserver = undefined
  if (!code) {
    fallbackHtml.value = ''
    rendererReady.value = false
    return
  }
  fallbackHtml.value = `<pre class="shiki shiki-fallback"><code>${escapeHtml(code)}</code></pre>`
  rendererReady.value = false
}

function clearFallback() {
  fallbackHtml.value = ''
  rendererReady.value = true
}

function clearRendererTarget() {
  if (rendererTarget.value)
    rendererTarget.value.innerHTML = ''
}

function hasRendererContent() {
  const target = rendererTarget.value
  if (!target)
    return false
  if (target.childNodes.length > 0)
    return true
  return Boolean(target.textContent?.trim().length)
}

async function clearFallbackWhenRendererReady(epoch: number) {
  await nextTick()
  if (!isCurrentRenderEpoch(epoch))
    return
  if (hasRendererContent()) {
    clearFallback()
    return
  }
  const target = rendererTarget.value
  if (!target)
    return
  renderObserver?.disconnect()
  const observer = new MutationObserver(() => {
    if (!isCurrentRenderEpoch(epoch)) {
      observer.disconnect()
      if (renderObserver === observer)
        renderObserver = undefined
      return
    }
    if (!hasRendererContent())
      return
    clearFallback()
    observer.disconnect()
    if (renderObserver === observer)
      renderObserver = undefined
  })
  renderObserver = observer
  observer.observe(target, { childList: true, subtree: true })
}
interface ShikiRenderer {
  updateCode: (code: string, lang?: string) => void | Promise<void>
  setTheme: (theme?: string) => void | Promise<void>
  dispose: () => void
}
type HighlightRegistrationStatus = 'ready' | 'failed' | 'stale'

let renderer: ShikiRenderer | undefined
let rendererConfigKey: string | null = null
let createShikiRenderer:
  | ((el: HTMLElement, opts: ShikiRendererOptions) => ShikiRenderer)
  | undefined
let registerHighlight:
  | ((opts?: RegisterHighlightOptions) => Promise<unknown> | unknown)
  | undefined
let defaultHighlightLanguages: string[] | undefined
let registeredHighlightLanguages: Set<string> | undefined
let registeredHighlightKey: string | null = null
let latestHighlightRegistrationKey = ''
let highlightRegistrationSeq = 0
let renderEpoch = 0
let disposed = false
const warnedMissingLanguages = new Set<string>()
const warnedRendererErrors = new Set<string>()
const isDevEnv = typeof import.meta !== 'undefined' && Boolean(import.meta.env?.DEV)
let streamMarkdownLoadPromise: Promise<void> | null = null

function nextRenderEpoch() {
  renderEpoch += 1
  return renderEpoch
}

function isCurrentRenderEpoch(epoch = renderEpoch) {
  return !disposed && epoch === renderEpoch
}

function disposeCurrentRenderer() {
  renderer?.dispose()
  renderer = undefined
  rendererConfigKey = null
  clearRendererTarget()
  rendererReady.value = false
}

function readDefaultLanguages(mod: unknown) {
  const maybeDefaults = (mod as { defaultLanguages?: unknown }).defaultLanguages
  if (!Array.isArray(maybeDefaults))
    return undefined

  const langs = maybeDefaults.filter((lang): lang is string => typeof lang === 'string')
  return langs.length ? langs : undefined
}

const highlightRegistrationKey = computed(() =>
  getHighlightRegistrationKey(props.themes, props.langs),
)

function normalizeRendererLanguage(rawLang?: string | null, hasContent = false) {
  const normalized = normalizeShikiLanguage(rawLang)
  if (!normalized)
    return 'plaintext'

  const matchKey = getShikiLanguageMatchKey(normalized)
  if (!registeredHighlightLanguages || registeredHighlightLanguages.has(matchKey))
    return normalized

  if (hasContent && isDevEnv && !warnedMissingLanguages.has(normalized)) {
    warnedMissingLanguages.add(normalized)
    console.warn(`[MarkdownCodeBlockNode] Language "${normalized}" not preloaded in stream-markdown; falling back to plaintext.`)
  }
  return 'plaintext'
}

async function updateRendererWithFallback(code: string, rawLang?: string | null, epoch = renderEpoch) {
  if (!renderer || !isCurrentRenderEpoch(epoch))
    return false
  const normalized = normalizeRendererLanguage(rawLang, Boolean(code && code.length))
  try {
    await renderer.updateCode(code, normalized)
    return isCurrentRenderEpoch(epoch)
  }
  catch (err) {
    if (!isCurrentRenderEpoch(epoch))
      return false

    if (normalized !== 'plaintext') {
      if (isDevEnv && !warnedRendererErrors.has(normalized)) {
        warnedRendererErrors.add(normalized)
        console.warn(`[MarkdownCodeBlockNode] Failed to render language "${normalized}", retrying as plaintext.`, err)
      }
      try {
        await renderer.updateCode(code, 'plaintext')
        return isCurrentRenderEpoch(epoch)
      }
      catch (plainErr) {
        if (!isCurrentRenderEpoch(epoch))
          return false
        if (isDevEnv)
          console.warn('[MarkdownCodeBlockNode] Failed to render code block even as plaintext.', plainErr)
        return false
      }
    }
    else if (isDevEnv) {
      console.warn('[MarkdownCodeBlockNode] Failed to render code block even as plaintext.', err)
    }
    return false
  }
}

async function ensureStreamMarkdownLoaded() {
  if (createShikiRenderer)
    return
  if (streamMarkdownLoadPromise)
    return streamMarkdownLoadPromise

  streamMarkdownLoadPromise = (async () => {
    try {
      const mod = await import('stream-markdown')
      createShikiRenderer = mod.createShikiStreamRenderer
      registerHighlight = mod.registerHighlight as NonNullable<typeof registerHighlight>
      defaultHighlightLanguages = readDefaultLanguages(mod)
    }
    catch (e) {
      if (isDevEnv)
        console.warn('[MarkdownCodeBlockNode] stream-markdown not available:', e)
    }
    finally {
      streamMarkdownLoadPromise = null
    }
  })()

  return streamMarkdownLoadPromise
}

async function ensureHighlightRegistered(themes?: readonly unknown[], langs?: readonly string[]): Promise<HighlightRegistrationStatus> {
  if (!registerHighlight)
    return 'ready'
  const opts = getEffectiveRegisterHighlightOptions(
    themes,
    langs,
    defaultHighlightLanguages,
  )
  const key = getHighlightRegistrationKey(opts.themes, opts.langs)
  if (latestHighlightRegistrationKey !== key)
    return 'stale'

  if (registeredHighlightKey === key)
    return 'ready'

  const seq = ++highlightRegistrationSeq

  try {
    await registerHighlightOnce(registerHighlight, opts, key)
  }
  catch {
    if (seq !== highlightRegistrationSeq || latestHighlightRegistrationKey !== key)
      return 'stale'
    return 'failed'
  }

  if (seq !== highlightRegistrationSeq || latestHighlightRegistrationKey !== key)
    return 'stale'

  registeredHighlightKey = key
  registeredHighlightLanguages = createRegisteredHighlightLanguages(opts.langs)
  return 'ready'
}

async function waitForCurrentHighlightRegistration(themes?: readonly unknown[], langs?: readonly string[]) {
  const opts = getEffectiveRegisterHighlightOptions(
    themes,
    langs,
    defaultHighlightLanguages,
  )
  const key = getHighlightRegistrationKey(opts.themes, opts.langs)
  const status = await ensureHighlightRegistered(themes, langs)
  if (status !== 'failed')
    return status

  if (latestHighlightRegistrationKey !== key)
    return 'stale'

  return ensureHighlightRegistered(themes, langs)
}

async function initRenderer(epoch: number) {
  if (!isCurrentRenderEpoch(epoch))
    return

  if (!viewportReady.value) {
    renderFallback(props.node.code)
    return
  }

  await ensureStreamMarkdownLoaded()
  if (!isCurrentRenderEpoch(epoch))
    return

  if (!codeBlockContent.value || !rendererTarget.value) {
    renderFallback(props.node.code)
    return
  }

  const rendererOptions = getEffectiveShikiRendererOptions(
    props.themes,
    props.langs,
    defaultHighlightLanguages,
  )
  const nextRendererConfigKey = getHighlightRegistrationKey(
    rendererOptions.themes,
    rendererOptions.langs,
  )
  latestHighlightRegistrationKey = nextRendererConfigKey

  if (renderer && rendererConfigKey !== nextRendererConfigKey)
    disposeCurrentRenderer()

  const highlightStatus = await waitForCurrentHighlightRegistration(
    rendererOptions.themes,
    rendererOptions.langs,
  )
  if (!isCurrentRenderEpoch(epoch) || highlightStatus === 'stale')
    return
  if (highlightStatus === 'failed') {
    renderFallback(props.node.code)
    return
  }

  if (!renderer && createShikiRenderer) {
    renderer = createShikiRenderer(rendererTarget.value, {
      theme: getPreferredColorScheme(),
      ...rendererOptions,
    })
    rendererConfigKey = nextRendererConfigKey
    rendererReady.value = true
  }

  if (!renderer) {
    renderFallback(props.node.code)
    return
  }

  if (props.stream === false && props.loading) {
    renderFallback(props.node.code)
    return
  }

  renderFallback(props.node.code)
  const rendered = await updateRendererWithFallback(props.node.code, props.node.language, epoch)
  if (!isCurrentRenderEpoch(epoch))
    return
  if (rendered)
    await clearFallbackWhenRendererReady(epoch)
}

async function safeInitRenderer(epoch = nextRenderEpoch()) {
  try {
    await initRenderer(epoch)
  }
  catch (err) {
    if (!isCurrentRenderEpoch(epoch))
      return
    if (isDevEnv)
      console.warn('[MarkdownCodeBlockNode] Failed to initialize Shiki renderer.', err)
    renderFallback(props.node.code)
  }
}
onMounted(() => {
  if (!viewportReady.value) {
    renderFallback(props.node.code)
    return
  }
  void safeInitRenderer()
})
onBeforeUnmount(() => {
  disposed = true
  renderEpoch += 1
  viewportHandle.value?.destroy()
  viewportHandle.value = null
  renderObserver?.disconnect()
  renderObserver = undefined
  disposeCurrentRenderer()
})

watch(highlightRegistrationKey, async () => {
  if (!viewportReady.value)
    return

  await safeInitRenderer()
})

watch(() => props.loading, (loading) => {
  if (loading)
    return
  if (!viewportReady.value) {
    renderFallback(props.node.code)
    return
  }
  void safeInitRenderer()
})

watch(() => viewportReady.value, (ready) => {
  if (!ready)
    return
  void safeInitRenderer()
})

watch(tooltipsEnabled, (enabled) => {
  if (!enabled)
    hideTooltip()
})

watch(() => props.autoScrollInitial, (enabled) => {
  autoScrollEnabled.value = enabled !== false
})

watch(() => [props.node.code, props.node.language], async ([code, lang]) => {
  const epoch = nextRenderEpoch()
  const normalizedLang = normalizeDisplayLanguage(lang)
  if (normalizedLang !== codeLanguage.value)
    codeLanguage.value = normalizedLang
  if (!viewportReady.value) {
    renderFallback(code)
    return
  }
  if (!codeBlockContent.value || !rendererTarget.value) {
    renderFallback(code)
    return
  }

  if (!renderer) {
    renderFallback(code)
    await safeInitRenderer(epoch)
  }
  if (!isCurrentRenderEpoch(epoch))
    return
  if (!renderer || !code)
    return

  if (props.stream === false && props.loading)
    return

  renderFallback(code)
  const rendered = await updateRendererWithFallback(code, lang, epoch)
  if (!isCurrentRenderEpoch(epoch))
    return
  if (rendered)
    await clearFallbackWhenRendererReady(epoch)
})

watch(
  () => [props.darkTheme, props.lightTheme, props.isDark],
  async () => {
    if (!viewportReady.value)
      return
    if (!codeBlockContent.value || !rendererTarget.value)
      return
    if (!renderer)
      await safeInitRenderer()
    renderer?.setTheme(getPreferredColorScheme())
  },
)

// Auto-scroll to bottom when content changes (if not expanded and auto-scroll is enabled)
watch(() => props.node.code, async () => {
  if (isExpanded.value || !shouldAutoScrollOnUpdate.value || !autoScrollEnabled.value)
    return

  await nextTick()
  const content = codeBlockContent.value
  if (!content)
    return

  // Check if content has scrollbar (scrollHeight > clientHeight)
  if (content.scrollHeight > content.clientHeight) {
    // Scroll to bottom
    content.scrollTop = content.scrollHeight
  }
})

// Check if user is at the bottom of scroll area
// Increased threshold to 50px to better detect "near bottom" state
function isAtBottom(element: HTMLElement, threshold = 50): boolean {
  return element.scrollHeight - element.scrollTop - element.clientHeight <= threshold
}

// Handle scroll event to detect user interaction
function handleScroll() {
  const content = codeBlockContent.value
  if (!content || isExpanded.value || !shouldAutoScrollOnUpdate.value)
    return

  const currentScrollTop = content.scrollTop

  // Detect scroll direction: if user scrolls up (scrollTop decreased), disable auto-scroll immediately
  if (currentScrollTop < lastScrollTop.value) {
    // User is scrolling up - disable auto-scroll
    autoScrollEnabled.value = false
  }
  else if (isAtBottom(content)) {
    // User is scrolling down and near bottom - re-enable auto-scroll
    autoScrollEnabled.value = true
  }

  // Update last scroll position
  lastScrollTop.value = currentScrollTop
}

// Copy code functionality
async function copy() {
  try {
    if (typeof navigator !== 'undefined' && navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {
      await navigator.clipboard.writeText(props.node.code)
    }
    copyText.value = true
    emits('copy', props.node.code)
    setTimeout(() => {
      copyText.value = false
    }, 1000)
  }
  catch (err) {
    console.error('Copy failed:', err)
  }
}

// Tooltip helpers
function resolveTooltipTarget(e: Event) {
  const btn = (e.currentTarget || e.target) as HTMLButtonElement | null
  if (!btn || btn.disabled)
    return null
  return btn
}

// Expand/collapse functionality
function toggleExpand(e?: Event) {
  isExpanded.value = !isExpanded.value

  if (e && tooltipsEnabled.value) {
    const target = resolveTooltipTarget(e)
    if (target) {
      const txt = isExpanded.value ? (t('common.collapse') || 'Collapse') : (t('common.expand') || 'Expand')
      showTooltipForAnchor(target, txt, 'top', false, undefined, props.isDark)
    }
  }

  const content = codeBlockContent.value
  if (!content)
    return

  if (isExpanded.value) {
    content.style.maxHeight = 'none'
    content.style['overflow-y'] = 'visible'
    content.style['overflow-x'] = 'auto'
  }
  else {
    content.style.maxHeight = ''
    content.style.overflow = 'auto'
    if (shouldAutoScrollOnUpdate.value) {
      autoScrollEnabled.value = true
      nextTick(() => {
        if (content.scrollHeight > content.clientHeight) {
          content.scrollTop = content.scrollHeight
        }
      })
    }
  }
}

// Header collapse/fold functionality
function toggleHeaderCollapse() {
  isCollapsed.value = !isCollapsed.value
}

// Font size controls
function increaseCodeFont() {
  const after = Math.min(codeFontMax, codeFontSize.value + codeFontStep)
  codeFontSize.value = after
}

function decreaseCodeFont() {
  const after = Math.max(codeFontMin, codeFontSize.value - codeFontStep)
  codeFontSize.value = after
}

function resetCodeFont() {
  codeFontSize.value = defaultCodeFontSize.value
}

// Preview functionality
function previewCode() {
  if (!isPreviewable.value)
    return

  const lowerLang = normalizeDisplayLanguage(codeLanguage.value || props.node.language).toLowerCase()
  const artifactType = lowerLang === 'html' ? 'text/html' : 'image/svg+xml'
  const artifactTitle
    = lowerLang === 'html'
      ? 'HTML Preview'
      : 'SVG Preview'

  emits('previewCode', {
    type: artifactType,
    content: props.node.code,
    title: artifactTitle,
  })
}
</script>

<template>
  <div
    ref="container"
    :style="containerStyle"
    class="code-block-container rounded-lg border overflow-hidden"
    :class="{ dark: props.isDark }"
  >
    <CodeBlockShell
      :show-header="props.showHeader"
      :show-collapse-button="props.showCollapseButton"
      :show-font-size-buttons="props.showFontSizeButtons"
      :enable-font-size-control="props.enableFontSizeControl"
      :show-copy-button="props.showCopyButton"
      :show-expand-button="props.showExpandButton"
      :show-preview-button="props.showPreviewButton"
      :show-tooltips="props.showTooltips"
      :is-dark="props.isDark"
      :loading="props.loading"
      :stream="props.stream"
      :is-collapsed="isCollapsed"
      :is-expanded="isExpanded"
      :copy-text="copyText"
      :is-previewable="isPreviewable"
      :code-font-size="codeFontSize"
      :code-font-min="codeFontMin"
      :code-font-max="codeFontMax"
      :default-code-font-size="defaultCodeFontSize"
      :font-baseline-ready="fontBaselineReady"
      @toggle-collapse="toggleHeaderCollapse"
      @decrease-font="decreaseCodeFont"
      @reset-font="resetCodeFont"
      @increase-font="increaseCodeFont"
      @copy="copy"
      @toggle-expand="toggleExpand"
      @preview="previewCode"
    >
      <template #header-left>
        <slot name="header-left">
          <div class="code-header-main">
            <span class="icon-slot h-4 w-4 flex-shrink-0" v-html="languageIcon" />
            <div class="code-header-copy">
              <div class="code-header-title">
                {{ displayLanguage }}
              </div>
            </div>
          </div>
        </slot>
      </template>
      <template v-if="$slots['header-right']" #header-right>
        <slot name="header-right" />
      </template>

      <!-- Content area -->
      <div
        ref="codeBlockContent"
        class="code-block-content"
        :style="contentStyle"
        @scroll="handleScroll"
      >
        <div ref="rendererTarget" class="code-block-render" />
        <div v-if="!rendererReady" class="code-fallback-plain" v-html="fallbackHtml" />
      </div>

      <template #loading>
        <slot name="loading" :loading="loading" :stream="stream">
          <div class="loading-skeleton">
            <div class="skeleton-line" />
            <div class="skeleton-line" />
            <div class="skeleton-line short" />
          </div>
        </slot>
      </template>
    </CodeBlockShell>
  </div>
</template>

<style scoped>
/* ── Code content ── */
.code-block-content {
  display: grid;
  max-height: min(70vh, var(--ms-size-code-max-height));
  overflow: auto;
  transition: max-height var(--ms-duration-slow) var(--ms-ease-standard);
  font-family: var(
    --markstream-code-font-family,
    ui-monospace,
    SFMono-Regular,
    SF Mono,
    Menlo,
    Monaco,
    Consolas,
    Liberation Mono,
    Courier New,
    monospace
  );
  font-size: var(--vscode-editor-font-size, 14px);
  line-height: var(--vscode-editor-line-height, 1.5);
}

.code-block-render,
.code-fallback-plain {
  grid-area: 1 / 1;
  min-width: 0;
}

.code-block-render {
  min-height: 1px;
}

:deep(.code-block-render pre),
:deep(.code-block-content .shiki) {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}

:deep(.code-block-content pre) {
  box-sizing: border-box;
  margin: 0;
  padding: 1rem;
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
}

:deep(.code-block-content .shiki-fallback) {
  background: transparent;
  color: inherit;
  white-space: pre;
}

.code-fallback-plain {
  white-space: pre;
  overflow: auto;
  background: transparent;
  color: inherit;
  font-size: inherit;
  line-height: inherit;
  font-family: inherit;
}

/* ── Loading placeholder ── */
.code-loading-placeholder {
  padding: 1rem;
  min-height: var(--ms-size-skeleton-min-height);
}

.loading-skeleton {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.skeleton-line {
  height: 1rem;
  background: linear-gradient(90deg, var(--loading-shimmer) 25%, hsl(var(--ms-muted-foreground) / 0.12) 37%, var(--loading-shimmer) 63%);
  background-size: 400% 100%;
  animation: code-skeleton-shimmer 1.2s ease-in-out infinite;
  border-radius: calc(var(--ms-radius) * 0.5);
}

.skeleton-line.short {
  width: 60%;
}

@keyframes code-skeleton-shimmer {
  0% { background-position: 100% 0; }
  100% { background-position: 0 0; }
}
</style>

// packages/markstream-react/src/components/MarkdownCodeBlockNode/MarkdownCodeBlockNode.tsx
import type { VisibilityHandle } from '../../context/viewportPriority'
import type { CommonCodeBlockProps } from '../../types/component-props'
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { useViewportPriority } from '../../context/viewportPriority'
import { useSafeI18n } from '../../i18n/useSafeI18n'
import { hideTooltip, showTooltipForAnchor } from '../../tooltip/singletonTooltip'
import { getLanguageIcon, languageMap, normalizeLanguageIdentifier, subscribeLanguageIconsRevision } from '../../utils/languageIcon'

export interface MarkdownCodeBlockNodeProps extends CommonCodeBlockProps {
  node: {
    type: 'code_block'
    language: string
    code: string
    raw: string
    diff?: boolean
    originalCode?: string
    updatedCode?: string
  }
  loading?: boolean
  stream?: boolean
  darkTheme?: string
  lightTheme?: string
  isDark?: boolean
  isShowPreview?: boolean
  enableFontSizeControl?: boolean
  minWidth?: string | number
  maxWidth?: string | number
  showPreviewButton?: boolean
  showCollapseButton?: boolean
  showFontSizeButtons?: boolean
  showTooltips?: boolean
  onCopy?: (code: string) => void
  onPreviewCode?: (payload: { type: string, content: string, title: string }) => void
}

interface ShikiRenderer {
  updateCode: (code: string, lang?: string) => void | Promise<void>
  setTheme: (theme?: string) => void | Promise<void>
  dispose: () => void
}

interface RegisterHighlightOptions {
  themes?: string[]
  langs?: string[]
}

interface ShikiRendererOptions {
  theme?: string
  themes?: string[]
  langs?: string[]
}

type HighlightRegistrationStatus = 'ready' | 'failed' | 'stale'

const SHIKI_LANGUAGE_CANONICAL_ALIAS: Record<string, string> = {
  'plain': 'plaintext',
  'text': 'plaintext',
  'txt': 'plaintext',
  'cs': 'csharp',
  'objectivec': 'objective-c',
  'objective-c': 'objective-c',
  'objectivecpp': 'objective-cpp',
  'objective-c++': 'objective-cpp',
  'objective-cpp': 'objective-cpp',
}

function escapeHtml(str: string) {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function normalizeShikiLanguage(rawLang?: string | null) {
  const normalized = normalizeDisplayLanguage(rawLang)
  return SHIKI_LANGUAGE_CANONICAL_ALIAS[normalized] ?? normalized
}

function getLanguageBaseToken(rawLang?: string | null) {
  return String(rawLang ?? '').split(':')[0]?.trim() ?? ''
}

function normalizeDisplayLanguage(rawLang?: string | null) {
  return normalizeLanguageIdentifier(getLanguageBaseToken(rawLang))
}

function getShikiLanguageMatchKey(rawLang?: string | null) {
  return normalizeShikiLanguage(rawLang)
}

function getShikiLangs(langs?: readonly string[]) {
  const normalized = Array.isArray(langs)
    ? langs.map(lang => normalizeShikiLanguage(lang)).filter(Boolean)
    : []

  return normalized.length > 0
    ? Array.from(new Set(normalized))
    : undefined
}

function createRegisteredHighlightLanguages(langs?: readonly string[]) {
  const shikiLangs = getShikiLangs(langs)
  if (!shikiLangs?.length)
    return undefined

  return new Set(
    shikiLangs.map(lang => getShikiLanguageMatchKey(lang)),
  )
}

function normalizeRendererLanguageForRegistered(
  rawLang: string | null | undefined,
  registeredLanguages?: ReadonlySet<string>,
) {
  const normalized = normalizeShikiLanguage(rawLang)
  if (!normalized)
    return 'plaintext'

  if (!registeredLanguages || registeredLanguages.has(getShikiLanguageMatchKey(normalized)))
    return normalized

  return 'plaintext'
}

function getHighlightRegistrationKey(themes?: readonly string[], langs?: readonly string[]): string {
  const themesKey = Array.isArray(themes) && themes.length > 0
    ? themes.map(theme => String(theme)).join('\u0000')
    : ''
  const sortedLangs = getShikiLangs(langs)
    ?.map(lang => getShikiLanguageMatchKey(lang))
    .sort()
    .join('\u0000') ?? ''
  return `${themesKey}\u0000\u0000${sortedLangs}`
}

function getRegisterHighlightOptions(themes?: readonly string[], langs?: readonly string[]): RegisterHighlightOptions {
  const opts: RegisterHighlightOptions = {}
  if (Array.isArray(themes) && themes.length > 0)
    opts.themes = [...themes]
  const shikiLangs = getShikiLangs(langs)
  if (shikiLangs?.length)
    opts.langs = shikiLangs
  return opts
}

export function MarkdownCodeBlockNode(rawProps: MarkdownCodeBlockNodeProps) {
  const props: Required<Pick<
    MarkdownCodeBlockNodeProps,
    | 'loading'
    | 'stream'
    | 'darkTheme'
    | 'lightTheme'
    | 'isDark'
    | 'isShowPreview'
    | 'enableFontSizeControl'
    | 'showHeader'
    | 'showCopyButton'
    | 'showExpandButton'
    | 'showPreviewButton'
    | 'showCollapseButton'
    | 'showFontSizeButtons'
  >> & MarkdownCodeBlockNodeProps = {
    loading: true,
    stream: true,
    darkTheme: 'vitesse-dark',
    lightTheme: 'vitesse-light',
    isDark: false,
    isShowPreview: true,
    enableFontSizeControl: true,
    showHeader: true,
    showCopyButton: true,
    showExpandButton: true,
    showPreviewButton: true,
    showCollapseButton: true,
    showFontSizeButtons: true,
    ...rawProps,
  }

  const codeLanguage = useMemo(() => String(props.node.language ?? ''), [props.node.language])
  const canonicalLanguage = useMemo(() => normalizeDisplayLanguage(codeLanguage), [codeLanguage])
  const [languageIconsRevision, setLanguageIconsRevision] = useState(0)

  useEffect(() => {
    return subscribeLanguageIconsRevision(() => {
      setLanguageIconsRevision(v => v + 1)
    })
  }, [])

  const displayLanguage = useMemo(() => {
    const label = languageMap[canonicalLanguage] || canonicalLanguage
    if (!label)
      return 'Text'
    return label.charAt(0).toUpperCase() + label.slice(1)
  }, [canonicalLanguage])
  const languageIcon = useMemo(
    () => getLanguageIcon(canonicalLanguage),
    [canonicalLanguage, languageIconsRevision],
  )

  const { t } = useSafeI18n()

  const isPreviewable = useMemo(() => {
    if (!props.isShowPreview)
      return false
    return canonicalLanguage === 'html' || canonicalLanguage === 'svg'
  }, [canonicalLanguage, props.isShowPreview])

  const containerStyle = useMemo(() => {
    const style: Record<string, string> = {}
    const fmt = (v: string | number | undefined) => {
      if (v == null)
        return undefined
      return typeof v === 'number' ? `${v}px` : String(v)
    }
    const min = fmt(props.minWidth)
    const max = fmt(props.maxWidth)
    if (min)
      style.minWidth = min
    if (max)
      style.maxWidth = max
    return style
  }, [props.maxWidth, props.minWidth])

  const [copied, setCopied] = useState(false)
  const [isExpanded, setIsExpanded] = useState(false)
  const [isCollapsed, setIsCollapsed] = useState(false)
  const [fallbackHtml, setFallbackHtml] = useState('')
  const [rendererReady, setRendererReady] = useState(false)

  const [defaultFontSize, setDefaultFontSize] = useState<number>(14)
  const [fontSize, setFontSize] = useState<number>(defaultFontSize)
  const tooltipsEnabled = useMemo(() => props.showTooltips !== false, [props.showTooltips])

  const viewportTargetRef = useRef<HTMLDivElement | null>(null)
  const codeBlockContentRef = useRef<HTMLDivElement | null>(null)
  const rendererTargetRef = useRef<HTMLDivElement | null>(null)
  const rendererRef = useRef<ShikiRenderer | null>(null)
  const rendererConfigKeyRef = useRef('')
  const createRendererRef = useRef<null | ((el: HTMLElement, opts: ShikiRendererOptions) => ShikiRenderer)>(null)
  const importAttemptedRef = useRef(false)
  const registerHighlightRef = useRef<((opts?: RegisterHighlightOptions) => Promise<unknown> | unknown) | null>(null)
  const defaultHighlightLanguagesRef = useRef<string[] | undefined>()
  const registeredHighlightLanguagesRef = useRef<Set<string> | undefined>()
  const registeredKeyRef = useRef<string>('')
  const highlightRegistrationSeqRef = useRef(0)
  const latestRegistrationKeyRef = useRef('')
  const viewportHandleRef = useRef<VisibilityHandle | null>(null)
  const registerViewport = useViewportPriority()
  const [viewportReady, setViewportReady] = useState(() => typeof window === 'undefined')

  const getPreferredColorScheme = useCallback(() => {
    return props.isDark ? props.darkTheme : props.lightTheme
  }, [props.darkTheme, props.isDark, props.lightTheme])

  const renderFallback = useCallback((code: string) => {
    if (!code) {
      setFallbackHtml('')
      setRendererReady(false)
      return
    }
    setFallbackHtml(`<pre class="shiki shiki-fallback"><code>${escapeHtml(code)}</code></pre>`)
    setRendererReady(false)
  }, [])

  const clearFallback = useCallback(() => {
    setFallbackHtml('')
    setRendererReady(true)
  }, [])

  const ensureStreamMarkdownLoaded = useCallback(async () => {
    if (createRendererRef.current || importAttemptedRef.current)
      return
    importAttemptedRef.current = true
    try {
      const mod: any = await import('stream-markdown')
      createRendererRef.current = mod.createShikiStreamRenderer
      if (mod.registerHighlight)
        registerHighlightRef.current = mod.registerHighlight
      defaultHighlightLanguagesRef.current = Array.isArray(mod.defaultLanguages)
        ? mod.defaultLanguages
        : undefined
    }
    catch {
      // optional peer
    }
  }, [])

  const registrationKey = useMemo(
    () => getHighlightRegistrationKey(props.themes, props.langs),
    [props.themes, props.langs],
  )

  useEffect(() => {
    latestRegistrationKeyRef.current = registrationKey
  }, [registrationKey])

  const ensureHighlightRegistered = useCallback(async (): Promise<HighlightRegistrationStatus> => {
    if (!registerHighlightRef.current)
      return 'ready'
    const key = registrationKey
    latestRegistrationKeyRef.current = key

    if (registeredKeyRef.current === key)
      return 'ready'
    const opts = getRegisterHighlightOptions(props.themes, props.langs)
    const effectiveLangs = opts.langs ?? defaultHighlightLanguagesRef.current
    const seq = ++highlightRegistrationSeqRef.current

    try {
      await registerHighlightRef.current(opts)
    }
    catch {
      return 'failed'
    }

    if (seq !== highlightRegistrationSeqRef.current || latestRegistrationKeyRef.current !== key)
      return 'stale'

    registeredKeyRef.current = key
    registeredHighlightLanguagesRef.current = createRegisteredHighlightLanguages(effectiveLangs)
    return 'ready'
  }, [props.langs, props.themes, registrationKey])

  const waitForCurrentHighlightRegistration = useCallback(async () => {
    const status = await ensureHighlightRegistered()
    if (status !== 'failed')
      return status

    return ensureHighlightRegistered()
  }, [ensureHighlightRegistered])

  const updateRendererWithFallback = useCallback(async (code: string) => {
    const renderer = rendererRef.current
    if (!renderer)
      return

    const lang = normalizeRendererLanguageForRegistered(
      codeLanguage,
      registeredHighlightLanguagesRef.current,
    )

    try {
      await renderer.updateCode(code, lang)
      clearFallback()
    }
    catch {
      if (lang === 'plaintext')
        return

      try {
        await renderer.updateCode(code, 'plaintext')
        clearFallback()
      }
      catch {
        // keep fallback
      }
    }
  }, [clearFallback, codeLanguage])

  const initRenderer = useCallback(async () => {
    if (!viewportReady) {
      renderFallback(props.node.code)
      return
    }

    await ensureStreamMarkdownLoaded()

    const highlightStatus = await waitForCurrentHighlightRegistration()
    if (highlightStatus === 'stale')
      return
    if (highlightStatus === 'failed') {
      renderFallback(props.node.code)
      return
    }

    if (!codeBlockContentRef.current || !rendererTargetRef.current) {
      renderFallback(props.node.code)
      return
    }

    if (rendererRef.current && rendererConfigKeyRef.current !== registrationKey) {
      rendererRef.current.dispose()
      rendererRef.current = null
      rendererConfigKeyRef.current = ''
      setRendererReady(false)
    }

    if (!rendererRef.current && createRendererRef.current) {
      rendererRef.current = createRendererRef.current(rendererTargetRef.current, {
        theme: getPreferredColorScheme(),
        themes: props.themes,
        langs: getShikiLangs(props.langs),
      })
      rendererConfigKeyRef.current = registrationKey
      setRendererReady(true)
    }

    if (!rendererRef.current) {
      renderFallback(props.node.code)
      return
    }

    if (props.stream === false && props.loading) {
      renderFallback(props.node.code)
      return
    }

    renderFallback(props.node.code)
    await updateRendererWithFallback(props.node.code)
  }, [
    ensureStreamMarkdownLoaded,
    getPreferredColorScheme,
    registrationKey,
    waitForCurrentHighlightRegistration,
    props.langs,
    props.loading,
    props.node.code,
    props.stream,
    props.themes,
    renderFallback,
    updateRendererWithFallback,
    viewportReady,
  ])

  useEffect(() => {
    const el = viewportTargetRef.current
    if (!el)
      return
    const handle = registerViewport(el, { rootMargin: '400px' })
    viewportHandleRef.current = handle
    if (handle.isVisible())
      setViewportReady(true)
    handle.whenVisible.then(() => setViewportReady(true))
    return () => {
      handle.destroy()
      viewportHandleRef.current = null
    }
  }, [registerViewport])

  useEffect(() => {
    void initRenderer().catch(() => {
      renderFallback(props.node.code)
    })
  }, [initRenderer, props.node.code, renderFallback])

  // Dispose renderer on unmount only
  useEffect(() => {
    return () => {
      rendererRef.current?.dispose()
      rendererRef.current = null
      rendererConfigKeyRef.current = ''
    }
  }, [])

  useEffect(() => {
    if (!rendererRef.current)
      return
    if (!viewportReady)
      return
    void rendererRef.current.setTheme(getPreferredColorScheme())
  }, [getPreferredColorScheme, viewportReady])

  useEffect(() => {
    if (!tooltipsEnabled)
      hideTooltip(true)
  }, [tooltipsEnabled])

  const onBtnHover = useCallback((event: React.MouseEvent<HTMLElement> | React.FocusEvent<HTMLElement>, text: string) => {
    if (!tooltipsEnabled)
      return
    const btn = event.currentTarget as unknown as HTMLElement
    if (!btn || (btn as HTMLButtonElement).disabled)
      return
    const origin = 'clientX' in event
      ? { x: event.clientX, y: event.clientY }
      : undefined
    showTooltipForAnchor(btn, text, 'top', false, origin, props.isDark)
  }, [props.isDark, tooltipsEnabled])

  const onBtnLeave = useCallback(() => {
    if (!tooltipsEnabled)
      return
    hideTooltip()
  }, [tooltipsEnabled])

  const copy = useCallback(async () => {
    try {
      if (typeof navigator !== 'undefined' && navigator.clipboard && typeof navigator.clipboard.writeText === 'function')
        await navigator.clipboard.writeText(props.node.code)
      setCopied(true)
      props.onCopy?.(props.node.code)
      setTimeout(() => setCopied(false), 1000)
    }
    catch {}
  }, [props])

  const previewCode = useCallback(() => {
    if (!isPreviewable)
      return
    const lowerLang = canonicalLanguage
    const artifactType = lowerLang === 'html' ? 'text/html' : 'image/svg+xml'
    const artifactTitle = lowerLang === 'html' ? 'HTML Preview' : 'SVG Preview'
    props.onPreviewCode?.({
      type: artifactType,
      content: props.node.code,
      title: artifactTitle,
    })
  }, [canonicalLanguage, isPreviewable, props])

  const contentStyle = useMemo(() => ({ fontSize: `${fontSize}px` }), [fontSize])

  const decreaseCodeFont = () => setFontSize(s => Math.max(10, s - 1))
  const increaseCodeFont = () => setFontSize(s => Math.min(36, s + 1))
  const resetCodeFont = () => setFontSize(defaultFontSize)

  useEffect(() => {
    const initial = 14
    setDefaultFontSize(initial)
    setFontSize(initial)
  }, [])

  return (
    <div
      ref={viewportTargetRef}
      className={[
        'code-block-container my-4 rounded-lg border overflow-hidden shadow-sm',
        props.isDark ? 'border-gray-700/30 bg-gray-900 is-dark' : 'border-gray-200 bg-white',
      ].join(' ')}
      style={containerStyle}
    >
      {props.showHeader && (
        <div
          className="code-block-header flex justify-between items-center px-4 py-2.5 border-b border-gray-400/5"
          style={{ color: 'var(--vscode-editor-foreground)', backgroundColor: 'var(--vscode-editor-background)' }}
        >
          <div className="flex items-center space-x-2">
            <span
              className="icon-slot h-4 w-4 flex-shrink-0"
              // language icons are trusted internal assets or user-supplied via resolver
              dangerouslySetInnerHTML={{ __html: languageIcon }}
            />
            <span className="text-sm font-medium font-mono">{displayLanguage}</span>
          </div>
          <div className="flex items-center space-x-2">
            {props.showCollapseButton && (
              <button
                type="button"
                className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                aria-pressed={isCollapsed}
                onClick={() => setIsCollapsed(v => !v)}
                onMouseEnter={e => onBtnHover(e, isCollapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))}
                onFocus={e => onBtnHover(e as any, isCollapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))}
                onMouseLeave={onBtnLeave}
                onBlur={onBtnLeave}
              >
                <svg
                  style={{ rotate: isCollapsed ? '0deg' : '90deg' }}
                  xmlns="http://www.w3.org/2000/svg"
                  xmlnsXlink="http://www.w3.org/1999/xlink"
                  aria-hidden="true"
                  role="img"
                  width="1em"
                  height="1em"
                  viewBox="0 0 24 24"
                  className="w-3 h-3"
                >
                  <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m9 18l6-6l-6-6" />
                </svg>
              </button>
            )}

            {props.showFontSizeButtons && props.enableFontSizeControl && (
              <>
                <button
                  type="button"
                  className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                  disabled={fontSize <= 10}
                  onClick={decreaseCodeFont}
                  onMouseEnter={e => onBtnHover(e, t('common.decrease') || 'Decrease')}
                  onFocus={e => onBtnHover(e as any, t('common.decrease') || 'Decrease')}
                  onMouseLeave={onBtnLeave}
                  onBlur={onBtnLeave}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    aria-hidden="true"
                    role="img"
                    width="1em"
                    height="1em"
                    viewBox="0 0 24 24"
                    className="w-3 h-3"
                  >
                    <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h14" />
                  </svg>
                </button>
                <button
                  type="button"
                  className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                  disabled={fontSize === defaultFontSize}
                  onClick={resetCodeFont}
                  onMouseEnter={e => onBtnHover(e, t('common.reset') || 'Reset')}
                  onFocus={e => onBtnHover(e as any, t('common.reset') || 'Reset')}
                  onMouseLeave={onBtnLeave}
                  onBlur={onBtnLeave}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    aria-hidden="true"
                    role="img"
                    width="1em"
                    height="1em"
                    viewBox="0 0 24 24"
                    className="w-3 h-3"
                  >
                    <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2">
                      <path d="M3 12a9 9 0 1 0 9-9a9.75 9.75 0 0 0-6.74 2.74L3 8" />
                      <path d="M3 3v5h5" />
                    </g>
                  </svg>
                </button>
                <button
                  type="button"
                  className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                  disabled={fontSize >= 36}
                  onClick={increaseCodeFont}
                  onMouseEnter={e => onBtnHover(e, t('common.increase') || 'Increase')}
                  onFocus={e => onBtnHover(e as any, t('common.increase') || 'Increase')}
                  onMouseLeave={onBtnLeave}
                  onBlur={onBtnLeave}
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    xmlnsXlink="http://www.w3.org/1999/xlink"
                    aria-hidden="true"
                    role="img"
                    width="1em"
                    height="1em"
                    viewBox="0 0 24 24"
                    className="w-3 h-3"
                  >
                    <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h14m-7-7v14" />
                  </svg>
                </button>
              </>
            )}

            {props.showCopyButton && (
              <button
                type="button"
                className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                aria-label={copied ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy')}
                onClick={copy}
                onMouseEnter={e => onBtnHover(e, copied ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy'))}
                onFocus={e => onBtnHover(e as any, copied ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy'))}
                onMouseLeave={onBtnLeave}
                onBlur={onBtnLeave}
              >
                {!copied
                  ? (
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlnsXlink="http://www.w3.org/1999/xlink"
                        aria-hidden="true"
                        role="img"
                        width="1em"
                        height="1em"
                        viewBox="0 0 24 24"
                        className="w-3 h-3"
                      >
                        <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2">
                          <rect width="14" height="14" x="8" y="8" rx="2" ry="2" />
                          <path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2" />
                        </g>
                      </svg>
                    )
                  : (
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlnsXlink="http://www.w3.org/1999/xlink"
                        aria-hidden="true"
                        role="img"
                        width="1em"
                        height="1em"
                        viewBox="0 0 24 24"
                        className="w-3 h-3"
                      >
                        <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M20 6L9 17l-5-5" />
                      </svg>
                    )}
              </button>
            )}

            {props.showExpandButton && (
              <button
                type="button"
                className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                aria-pressed={isExpanded}
                onClick={(e) => {
                  setIsExpanded(v => !v)
                  onBtnHover(e, !isExpanded ? (t('common.collapse') || 'Collapse') : (t('common.expand') || 'Expand'))
                }}
                onMouseEnter={e => onBtnHover(e, isExpanded ? (t('common.collapse') || 'Collapse') : (t('common.expand') || 'Expand'))}
                onFocus={e => onBtnHover(e as any, isExpanded ? (t('common.collapse') || 'Collapse') : (t('common.expand') || 'Expand'))}
                onMouseLeave={onBtnLeave}
                onBlur={onBtnLeave}
              >
                {isExpanded
                  ? (
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlnsXlink="http://www.w3.org/1999/xlink"
                        aria-hidden="true"
                        role="img"
                        width="1em"
                        height="1em"
                        viewBox="0 0 24 24"
                        className="w-3 h-3"
                      >
                        <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m14 10l7-7m-1 7h-6V4M3 21l7-7m-6 0h6v6" />
                      </svg>
                    )
                  : (
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        xmlnsXlink="http://www.w3.org/1999/xlink"
                        aria-hidden="true"
                        role="img"
                        width="1em"
                        height="1em"
                        viewBox="0 0 24 24"
                        className="w-3 h-3"
                      >
                        <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M15 3h6v6m0-6l-7 7M3 21l7-7m-1 7H3v-6" />
                      </svg>
                    )}
              </button>
            )}

            {isPreviewable && props.showPreviewButton && (
              <button
                type="button"
                className="code-action-btn p-2 text-xs rounded-md transition-colors hover:bg-[var(--vscode-editor-selectionBackground)]"
                aria-label={t('common.preview') || 'Preview'}
                onClick={previewCode}
                onMouseEnter={e => onBtnHover(e, t('common.preview') || 'Preview')}
                onFocus={e => onBtnHover(e as any, t('common.preview') || 'Preview')}
                onMouseLeave={onBtnLeave}
                onBlur={onBtnLeave}
              >
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  xmlnsXlink="http://www.w3.org/1999/xlink"
                  aria-hidden="true"
                  role="img"
                  width="1em"
                  height="1em"
                  viewBox="0 0 24 24"
                  className="w-3 h-3"
                >
                  <g fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2">
                    <path d="M2.062 12.348a1 1 0 0 1 0-.696a10.75 10.75 0 0 1 19.876 0a1 1 0 0 1 0 .696a10.75 10.75 0 0 1-19.876 0" />
                    <circle cx="12" cy="12" r="3" />
                  </g>
                </svg>
              </button>
            )}
          </div>
        </div>
      )}

      {!isCollapsed && (props.stream ? true : !props.loading) && (
        <div
          ref={codeBlockContentRef}
          className="code-block-content"
          style={{
            ...contentStyle,
            maxHeight: isExpanded ? 'none' : '500px',
            overflowY: isExpanded ? 'visible' : 'auto',
            overflowX: 'auto',
          }}
        >
          <div ref={rendererTargetRef} className="code-block-render" />
          {!rendererReady && fallbackHtml && (
            <div className="code-fallback-plain" dangerouslySetInnerHTML={{ __html: fallbackHtml }} />
          )}
        </div>
      )}

      {!props.stream && props.loading && (
        <div className="code-loading-placeholder">
          <div className="loading-skeleton">
            <div className="skeleton-line" />
            <div className="skeleton-line" />
            <div className="skeleton-line short" />
          </div>
        </div>
      )}
      <span className="sr-only" aria-live="polite" role="status">{copied ? (t('common.copied') || 'Copied') : ''}</span>
    </div>
  )
}

export default MarkdownCodeBlockNode
