// packages/markstream-vue2/src/components/MathInlineNode/MathInlineNode.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue-demi'
import { useViewportPriority } from '../../composables/viewportPriority'
import { getCachedMathRender, setCachedMathRender } from '../../utils/mathRenderCache'
import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../../workers/katexWorkerClient'
import { getKatex } from './katex'

interface MathInlineNodeProps {
  node: {
    type: 'math_inline'
    content: string
    raw: string
    loading?: boolean
    markup?: string
  }
  indexKey?: number | string
}

const props = defineProps<MathInlineNodeProps>()

const containerEl = ref<HTMLElement | null>(null)
const registerVisibility = useViewportPriority()
let visibilityHandle: ReturnType<typeof registerVisibility> | null = null
let currentRenderId = 0
let isUnmounted = false
let currentAbortController: AbortController | null = null

const displayMode = computed(() => props.node.markup === '$$')
const cacheKey = computed(() => {
  if (props.indexKey == null)
    return null
  return `inline:${String(props.indexKey)}`
})

const initialCached = getCachedMathRender(cacheKey.value)
const renderedHtml = ref(initialCached?.html || '')
const fallbackText = ref('')
const renderingLoading = ref(!initialCached?.html)
let hasRenderedOnce = Boolean(initialCached?.html)

async function renderWithMainThreadFallback() {
  const katex = await getKatex()
  if (!katex)
    return false
  try {
    const html = katex.renderToString(props.node.content, {
      throwOnError: props.node.loading,
      displayMode: displayMode.value,
    })
    applySuccessfulRender(html)
    setKaTeXCache(props.node.content, displayMode.value, html)
    return true
  }
  catch {
    return false
  }
}

function applySuccessfulRender(html: string) {
  renderedHtml.value = html
  fallbackText.value = ''
  renderingLoading.value = false
  hasRenderedOnce = true
  setCachedMathRender(cacheKey.value, html)
}

function applyRawFallback() {
  renderedHtml.value = ''
  fallbackText.value = props.node.raw
  renderingLoading.value = false
}

async function renderMath() {
  if (isUnmounted)
    return

  if (!props.node.content) {
    applyRawFallback()
    hasRenderedOnce = true
    return
  }

  const cached = getCachedMathRender(cacheKey.value)
  if (cached?.html && !renderedHtml.value) {
    renderedHtml.value = cached.html
    hasRenderedOnce = true
    renderingLoading.value = false
  }

  if (currentAbortController) {
    currentAbortController.abort()
    currentAbortController = null
  }

  const renderId = ++currentRenderId
  const abortController = new AbortController()
  currentAbortController = abortController

  if (!hasRenderedOnce) {
    renderingLoading.value = true
    try {
      if (!visibilityHandle && containerEl.value)
        visibilityHandle = registerVisibility(containerEl.value)
      await visibilityHandle?.whenVisible
    }
    catch {}
  }

  try {
    const html = await renderKaTeXWithBackpressure(props.node.content, displayMode.value, {
      timeout: 1500,
      waitTimeout: 0,
      maxRetries: 0,
      signal: abortController.signal,
    })
    if (isUnmounted || renderId !== currentRenderId)
      return
    applySuccessfulRender(html)
  }
  catch (err: any) {
    if (isUnmounted || renderId !== currentRenderId)
      return
    if (err?.name === 'AbortError')
      return

    const code = err?.code || err?.name
    const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || err?.fallbackToRenderer
    const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
    const isDisabled = code === 'KATEX_DISABLED'

    if ((isWorkerInitFailure || isBusyOrTimeout) && await renderWithMainThreadFallback())
      return

    if (hasRenderedOnce || renderedHtml.value)
      return

    if (isDisabled || !props.node.loading)
      applyRawFallback()
    else
      renderingLoading.value = true
  }
}

watch(
  () => [props.node.content, props.node.loading, props.node.markup, props.node.raw, props.indexKey],
  () => renderMath(),
)

onMounted(() => {
  renderMath()
})

onBeforeUnmount(() => {
  isUnmounted = true
  if (currentAbortController) {
    currentAbortController.abort()
    currentAbortController = null
  }
  visibilityHandle?.destroy?.()
  visibilityHandle = null
})
</script>

<template>
  <span ref="containerEl" class="math-inline-wrapper">
    <span v-if="renderedHtml" class="math-inline" v-html="renderedHtml" />
    <span v-else-if="fallbackText" class="math-inline math-inline--fallback">{{ fallbackText }}</span>
    <span
      v-if="renderingLoading && !renderedHtml && !fallbackText"
      class="math-inline__loading"
      role="status"
      aria-live="polite"
    >
      <slot name="loading" :is-loading="renderingLoading">
        <span class="math-inline__spinner animate-spin" aria-hidden="true" />
        <span class="sr-only">Loading</span>
      </slot>
    </span>
  </span>
</template>

<style scoped>
.math-inline-wrapper {
  position: relative;
  display: inline-block;
}

.math-inline {
  display: inline-block;
  vertical-align: middle;
}

.math-inline--fallback {
  white-space: pre-wrap;
}

.math-inline__loading {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
}

.math-inline__spinner {
  width: 1rem;
  height: 1rem;
  border-radius: 9999px;
  border: 2px solid rgba(94, 104, 121, 0.25);
  border-top-color: rgba(94, 104, 121, 0.8);
  will-change: transform;
}

.sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>

// packages/markstream-react/src/components/Math/MathInlineNode.tsx
import type { VisibilityHandle } from '../../context/viewportPriority'
import type { MathInlineNodeProps } from '../../types/component-props'
import { useEffect, useRef, useState } from 'react'
import { useViewportPriority } from '../../context/viewportPriority'
import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../../workers/katexWorkerClient'
import { getKatex } from './katex'

export function MathInlineNode({ node }: MathInlineNodeProps) {
  const containerRef = useRef<HTMLSpanElement | null>(null)
  const mathRef = useRef<HTMLSpanElement | null>(null)
  const viewportHandleRef = useRef<VisibilityHandle | null>(null)
  const registerViewport = useViewportPriority()
  const [loading, setLoading] = useState(true)
  const [viewportReady, setViewportReady] = useState(() => typeof window === 'undefined')
  const renderIdRef = useRef(0)

  useEffect(() => {
    const el = containerRef.current
    if (!el)
      return
    const handle = registerViewport(el, { rootMargin: '400px' })
    viewportHandleRef.current = handle
    if (handle.isVisible())
      setViewportReady(true)
    handle.whenVisible.then(() => setViewportReady(true))
    return () => {
      handle.destroy()
      viewportHandleRef.current = null
    }
  }, [registerViewport])

  useEffect(() => {
    const content = node.content ?? ''
    if (!content) {
      if (mathRef.current)
        mathRef.current.innerHTML = ''
      setLoading(false)
      return
    }
    if (!viewportReady) {
      setLoading(true)
      return
    }

    let aborted = false
    const controller = new AbortController()
    const renderId = ++renderIdRef.current
    const displayMode = node.markup === '$$'
    renderKaTeXWithBackpressure(content, displayMode, {
      timeout: 1500,
      waitTimeout: 0,
      maxRetries: 0,
      signal: controller.signal,
    })
      .then((html) => {
        if (aborted || renderId !== renderIdRef.current)
          return
        if (mathRef.current) {
          mathRef.current.innerHTML = html
          setLoading(false)
        }
      })
      .catch(async (err: any) => {
        if (aborted || renderId !== renderIdRef.current)
          return
        if (!mathRef.current)
          return
        const code = err?.code || err?.name
        const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || err?.fallbackToRenderer
        const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
        if (isWorkerInitFailure || isBusyOrTimeout) {
          const katex = await getKatex()
          if (katex) {
            try {
              const html = katex.renderToString(content, {
                throwOnError: node.loading,
                displayMode,
              })
              if (!aborted && renderId === renderIdRef.current && mathRef.current) {
                mathRef.current.innerHTML = html
                setLoading(false)
                setKaTeXCache(content, displayMode, html)
              }
              return
            }
            catch {}
          }
        }
        if (!node.loading) {
          mathRef.current.textContent = node.raw
          setLoading(false)
        }
      })

    return () => {
      aborted = true
      controller.abort()
    }
  }, [node.content, node.loading, node.raw, node.markup, viewportReady])

  return (
    <span ref={containerRef} className="math-inline-wrapper">
      <span ref={mathRef} className={`math-inline${loading ? ' math-inline--hidden' : ''}`} />
      {loading && (
        <span className="math-inline__loading" role="status" aria-live="polite">
          <span className="math-inline__spinner" aria-hidden="true" />
          <span className="sr-only">Loading</span>
        </span>
      )}
    </span>
  )
}
