// packages/markstream-svelte/src/components/MathInlineNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { onDestroy } from 'svelte'
  import { getKatex } from '../optional/katex'
  import { normalizeKaTeXRenderInput } from '../utils/normalizeKaTeXRenderInput'
  import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../workers/katexWorkerClient'
  import { getString } from './shared/node-helpers'

  export let node: SvelteRenderableNode

  let mathEl: HTMLSpanElement | null = null
  let loading = true
  let destroyed = false
  let renderVersion = 0
  let hasRenderedOnce = false

  $: source = getString((node as any)?.content || (node as any)?.markup || (node as any)?.raw)
  $: raw = getString((node as any)?.raw || source)
  $: nodeLoading = (node as any)?.loading === true
  $: displayMode = String((node as any)?.markup || '') === '$$'
  $: renderKey = `${source}\n${raw}\n${nodeLoading ? '1' : '0'}\n${displayMode ? '1' : '0'}`
  $: if (mathEl)
    void renderMath(renderKey, source, raw, nodeLoading, displayMode)

  onDestroy(() => {
    destroyed = true
    renderVersion += 1
  })

  async function renderMath(_renderKey: string, currentSource: string, currentRaw: string, currentLoading: boolean, currentDisplayMode: boolean) {
    const target = mathEl
    if (!target)
      return

    const content = normalizeKaTeXRenderInput(currentSource)
    const version = ++renderVersion
    if (!content) {
      target.textContent = ''
      loading = false
      return
    }

    if (!hasRenderedOnce)
      loading = true

    const html = await resolveKatexMarkup(content, currentDisplayMode, currentLoading)
    if (destroyed || version !== renderVersion)
      return

    if (html) {
      target.innerHTML = html
      hasRenderedOnce = true
      loading = false
    }
    else if (!currentLoading) {
      target.textContent = currentRaw || content
      loading = false
    }
  }

  async function resolveKatexMarkup(content: string, currentDisplayMode: boolean, currentLoading: boolean) {
    try {
      return await renderKaTeXWithBackpressure(content, currentDisplayMode, {
        timeout: 1500,
        waitTimeout: 0,
        maxRetries: 0,
      })
    }
    catch (error: any) {
      const code = error?.code || error?.name
      const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || error?.fallbackToRenderer
      const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
      if (!isWorkerInitFailure && !isBusyOrTimeout)
        return null
    }

    const katex = await getKatex()
    if (!katex)
      return null

    try {
      const html = katex.renderToString(content, {
        throwOnError: currentLoading,
        displayMode: currentDisplayMode,
      })
      setKaTeXCache(content, currentDisplayMode, html)
      return html
    }
    catch {
      return null
    }
  }
</script>

<span class="math-inline-wrapper markstream-nested-math" data-display="inline" data-markstream-katex-managed="1">
  <span bind:this={mathEl} class={'math-inline' + (loading ? ' math-inline--hidden' : '')}></span>
  {#if loading}
    <span class="math-inline__loading" role="status" aria-live="polite">
      <span class="math-inline__spinner" aria-hidden="true"></span>
      <span class="sr-only">Loading</span>
    </span>
  {/if}
</span>

// packages/markstream-react/src/components/Math/MathInlineNode.tsx
import type { MathInlineNodeProps } from '../../types/component-props'
import { useEffect, useRef, useState } from 'react'
import { renderKaTeXWithBackpressure, setKaTeXCache, WORKER_BUSY_CODE } from '../../workers/katexWorkerClient'
import { getKatex } from './katex'

export function MathInlineNode({ node }: MathInlineNodeProps) {
  const containerRef = useRef<HTMLSpanElement | null>(null)
  const mathRef = useRef<HTMLSpanElement | null>(null)
  const [loading, setLoading] = useState(true)
  const renderIdRef = useRef(0)

  useEffect(() => {
    let aborted = false
    const controller = new AbortController()
    const renderId = ++renderIdRef.current
    const content = node.content ?? ''
    if (!content) {
      setLoading(false)
      return () => controller.abort()
    }

    const displayMode = node.markup === '$$'
    renderKaTeXWithBackpressure(content, displayMode, {
      timeout: 1500,
      waitTimeout: 0,
      maxRetries: 0,
      signal: controller.signal,
    })
      .then((html) => {
        if (aborted || renderId !== renderIdRef.current)
          return
        if (mathRef.current) {
          mathRef.current.innerHTML = html
          setLoading(false)
        }
      })
      .catch(async (err: any) => {
        if (aborted || renderId !== renderIdRef.current)
          return
        if (!mathRef.current)
          return
        const code = err?.code || err?.name
        const isWorkerInitFailure = code === 'WORKER_INIT_ERROR' || err?.fallbackToRenderer
        const isBusyOrTimeout = code === WORKER_BUSY_CODE || code === 'WORKER_TIMEOUT'
        if (isWorkerInitFailure || isBusyOrTimeout) {
          const katex = await getKatex()
          if (katex) {
            try {
              const html = katex.renderToString(content, {
                throwOnError: node.loading,
                displayMode,
              })
              if (!aborted && renderId === renderIdRef.current && mathRef.current) {
                mathRef.current.innerHTML = html
                setLoading(false)
                setKaTeXCache(content, displayMode, html)
              }
              return
            }
            catch {}
          }
        }
        if (!node.loading) {
          mathRef.current.textContent = node.raw
          setLoading(false)
        }
      })

    return () => {
      aborted = true
      controller.abort()
    }
  }, [node.content, node.loading, node.raw, node.markup])

  return (
    <span ref={containerRef} className="math-inline-wrapper">
      <span ref={mathRef} className={`math-inline${loading ? ' math-inline--hidden' : ''}`} />
      {loading && (
        <span className="math-inline__loading" role="status" aria-live="polite">
          <span className="math-inline__spinner" aria-hidden="true" />
          <span className="sr-only">Loading</span>
        </span>
      )}
    </span>
  )
}
